(() => {
'use strict';
function expandConcept(c){
  const t=c.t,f=c.f,base=c.id,raw=(c.formula||'').trim(),formula=/^(no formula|n\/a|none)$/i.test(raw)?'':raw,rel=c.related||[],common=c.caveat||'';
  return [
    {id:`${base}-L1`,category:c.cat,subcategory:c.sub,topic:t,difficulty:1,interviewFrequency:f,questionType:'Definition',question:`What is ${t}?`,shortAnswer:c.d,idealInterviewAnswer:`${c.d} ${c.why}`,deepExplanation:`${c.d} ${c.why} Key caveat: ${c.caveat}`,intuition:c.why,spanishExplanation:c.es,formula,variables:'',workedExample:'',commonMistake:common,interviewerTrap:c.trap_q,followUps:[`How does ${t} work mechanically?`,`Why does ${t} matter?`],relatedConcepts:rel,tags:[c.cat,c.sub,t,'foundation']},
    {id:`${base}-L2`,category:c.cat,subcategory:c.sub,topic:t,difficulty:2,interviewFrequency:f,questionType:formula?'Formula Recall':'Explain Like an Analyst',question:`How does ${t} work mechanically, and how would you calculate or derive it?`,shortAnswer:`${formula?`A useful formula or relationship is: ${raw}. `:''}${c.d}`,idealInterviewAnswer:`${formula?`A useful formula or relationship is: ${raw}. `:''}${c.d} In practice, ${c.why}`,deepExplanation:`${formula?`A useful formula or relationship is: ${raw}. `:''}${c.d} The economic point is: ${c.why} Caveat: ${c.caveat}`,intuition:c.why,spanishExplanation:c.es,formula,variables:'',workedExample:'',commonMistake:common,interviewerTrap:c.trap_q,followUps:[`Why does ${t} work?`,`What can make ${t} misleading?`],relatedConcepts:rel,tags:[c.cat,c.sub,t,'mechanics']},
    {id:`${base}-L3`,category:c.cat,subcategory:c.sub,topic:t,difficulty:3,interviewFrequency:f,questionType:'Intuition',question:`Why does ${t} matter, and when is it useful in CIB?`,shortAnswer:c.why,idealInterviewAnswer:`${c.why} ${c.d}`,deepExplanation:`Use ${t} when the analytical question matches what it measures. ${c.why} Do not lose the caveat: ${c.caveat}`,intuition:c.why,spanishExplanation:c.es,formula,variables:'',workedExample:'',commonMistake:common,interviewerTrap:c.trap_q,followUps:[`What are the limitations of ${t}?`,c.trap_q],relatedConcepts:rel,tags:[c.cat,c.sub,t,'intuition']},
    {id:`${base}-L4`,category:c.cat,subcategory:c.sub,topic:t,difficulty:4,interviewFrequency:Math.max(3,f-1),questionType:'Advanced Technical',question:`What are the main limitations, caveats or ways ${t} can mislead you?`,shortAnswer:c.caveat,idealInterviewAnswer:`The main caveat is that ${c.caveat} I would interpret it alongside ${rel.slice(0,3).join(', ')||'the underlying economics'} rather than in isolation.`,deepExplanation:`${c.caveat} The correct interpretation depends on the business model, accounting, market context and the exact decision being made. ${c.why}`,intuition:'A strong interview answer identifies both what a metric explains and what it leaves out.',spanishExplanation:c.es,formula,variables:'',workedExample:'',commonMistake:common,interviewerTrap:c.trap_q,followUps:[c.trap_q,`What would you cross-check before relying on ${t}?`],relatedConcepts:rel,tags:[c.cat,c.sub,t,'limitations']},
    {id:`${base}-L5`,category:c.cat,subcategory:c.sub,topic:t,difficulty:5,interviewFrequency:f,questionType:'Trick Question',question:c.trap_q,shortAnswer:c.trap_a,idealInterviewAnswer:c.trap_a,deepExplanation:`${c.trap_a} The underlying intuition is: ${c.why} Relevant caveat: ${c.caveat}`,intuition:c.why,spanishExplanation:c.es,formula,variables:'',workedExample:'',commonMistake:common,interviewerTrap:'⚠ INTERVIEW TRAP',followUps:[`How would you test that conclusion quantitatively?`,`What assumption could make the opposite conclusion reasonable?`],relatedConcepts:rel,tags:[c.cat,c.sub,t,'interview-trap']}
  ];
}
const BANK=[...(window.CORE_CONCEPTS||[]).flatMap(expandConcept),...(window.CASE_QUESTIONS||[])].map(q=>({...q,collection:(q.interviewFrequency===5&&(q.difficulty<=4||q.tags?.includes('interview-trap')))?'Core Interview Questions':(q.collection||'Evergreen Technical')}));
const FORMULAS=(()=>{const m=new Map();for(const q of BANK){if(!q.formula)continue;const k=`${q.topic}|${q.formula}`;if(!m.has(k))m.set(k,{topic:q.topic,category:q.category,formula:q.formula,variables:q.variables||'',interpretation:q.intuition||'',whenUsed:q.idealInterviewAnswer||'',commonMistake:q.commonMistake||''});}return [...m.values()];})();
const app=document.getElementById('app');
const DAY=86400000;
const DEFAULTS={theme:'system',dailyGoal:30,newPerDay:15,interviewType:'M&A Interview',interviewMinutes:20};
const S={view:'home',progress:new Map(),notes:new Map(),history:[],settings:{...DEFAULTS},session:null,query:'',formulaQuery:'',searchTimer:null};
const byId=new Map(BANK.map(q=>[q.id,q]));

// ---------- persistence ----------
function idb(){return new Promise((res,rej)=>{const r=indexedDB.open('CIBDrillDB',1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('progress'))d.createObjectStore('progress',{keyPath:'id'});if(!d.objectStoreNames.contains('notes'))d.createObjectStore('notes',{keyPath:'id'});if(!d.objectStoreNames.contains('history'))d.createObjectStore('history',{keyPath:'key',autoIncrement:true});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function getAll(store){const d=await idb();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);});}
async function put(store,val){const d=await idb();return new Promise((res,rej)=>{const r=d.transaction(store,'readwrite').objectStore(store).put(val);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function add(store,val){const d=await idb();return new Promise((res,rej)=>{const r=d.transaction(store,'readwrite').objectStore(store).add(val);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function clearStore(store){const d=await idb();return new Promise((res,rej)=>{const r=d.transaction(store,'readwrite').objectStore(store).clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}
async function load(){
  S.settings={...DEFAULTS,...JSON.parse(localStorage.getItem('cib-settings')||'{}')};
  (await getAll('progress')).forEach(x=>S.progress.set(x.id,x));
  (await getAll('notes')).forEach(x=>S.notes.set(x.id,x.text||''));
  S.history=await getAll('history');
  applyTheme();
}
function saveSettings(){localStorage.setItem('cib-settings',JSON.stringify(S.settings));applyTheme();}
function baseProgress(id){return {id,reviews:0,ratingHistory:[],lastReview:null,nextReview:0,interval:0,difficulty:5,stability:.4,mastery:0,lapses:0,bookmarked:false};}
function prog(id){return S.progress.get(id)||baseProgress(id);}
function retrieval(p,now=Date.now()){if(!p.lastReview||!p.stability)return 1;const elapsed=Math.max(0,(now-new Date(p.lastReview).getTime())/DAY);return Math.exp(Math.log(.9)*elapsed/Math.max(.1,p.stability));}
function calcMastery(p){if(!p.reviews)return 0;const rs=p.ratingHistory.slice(-12);const perf=rs.reduce((a,r)=>a+({again:0,hard:.45,good:.78,easy:1}[r]??0),0)/Math.max(1,rs.length);const stab=Math.min(1,Math.log1p(p.stability)/Math.log(61));const ret=Math.min(1,retrieval(p));const diff=1-(p.difficulty-1)/9;const lapse=Math.max(0,1-p.lapses/Math.max(3,p.reviews));return Math.round(100*(.32*stab+.28*perf+.2*ret+.1*diff+.1*lapse));}
function schedule(prev,rating){
  const p={...baseProgress(prev.id),...prev};
  const now=Date.now(); let d=p.difficulty||5, st=p.stability||.4, interval;
  if(rating==='again'){d=Math.min(10,d+1.2);st=Math.max(.12,st*.45);interval=Math.max(.02,Math.min(.25,st*.18));p.lapses=(p.lapses||0)+1;}
  if(rating==='hard'){d=Math.min(10,d+.35);st=Math.max(.35,st*1.28);interval=Math.max(.5,st*.85);}
  if(rating==='good'){d=Math.max(1,d-.2);st=Math.max(1,st*(1.7+.055*(10-d)));interval=Math.max(1,st);}
  if(rating==='easy'){d=Math.max(1,d-.7);st=Math.max(2,st*(2.35+.075*(10-d)));interval=Math.max(3,st*1.25);}
  p.reviews=(p.reviews||0)+1;p.ratingHistory=[...(p.ratingHistory||[]),rating].slice(-40);p.lastReview=new Date(now).toISOString();p.interval=Math.round(interval*100)/100;p.nextReview=now+interval*DAY;p.difficulty=Math.round(d*100)/100;p.stability=Math.round(st*100)/100;p.mastery=calcMastery(p);return p;
}
async function rate(id,rating){const p=schedule(prog(id),rating);S.progress.set(id,p);await put('progress',p);const q=byId.get(id);const h={id,rating,ts:new Date().toISOString(),category:q?.category,topic:q?.topic,difficulty:q?.difficulty};S.history.push(h);await add('history',h);markStudyDay();if(S.session){S.session.ratings[id]=rating;if(rating==='again'){const q=byId.get(id);const insertAt=Math.min(S.session.qs.length,S.session.index+4);S.session.qs.splice(insertAt,0,q);}nextQuestion();}else render();}
function markStudyDay(){const today=dayKey(new Date());let d=JSON.parse(localStorage.getItem('cib-study-days')||'[]');if(!d.includes(today)){d.push(today);d=d.slice(-500);localStorage.setItem('cib-study-days',JSON.stringify(d));}}
function dayKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function streak(){const set=new Set(JSON.parse(localStorage.getItem('cib-study-days')||'[]'));let n=0,d=new Date();for(;;){if(set.has(dayKey(d)))n++;else break;d=new Date(d.getTime()-DAY);}return n;}

// ---------- queue / analytics ----------
function shuffled(xs){const a=[...xs];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function due(){const now=Date.now();return BANK.filter(q=>{const p=prog(q.id);return p.reviews>0&&(p.nextReview||0)<=now;}).sort((a,b)=>(prog(a.id).nextReview||0)-(prog(b.id).nextReview||0));}
function unseen(){return BANK.filter(q=>!prog(q.id).reviews);}
function topicStats(){const m=new Map();for(const q of BANK){const p=prog(q.id);if(!m.has(q.subcategory))m.set(q.subcategory,{n:0,sum:0,reviewed:0});const x=m.get(q.subcategory);x.n++;if(p.reviews){x.reviewed++;x.sum+=p.mastery||0;}}return [...m].map(([name,x])=>({name,mastery:x.reviewed?Math.round(x.sum/x.reviewed):0,reviewed:x.reviewed,total:x.n})).filter(x=>x.reviewed).sort((a,b)=>a.mastery-b.mastery);}
function weakQuestions(){const weak=new Set(topicStats().slice(0,8).map(x=>x.name));return BANK.filter(q=>weak.has(q.subcategory)).sort((a,b)=>(prog(a.id).mastery||0)-(prog(b.id).mastery||0));}
function totalStudyMinutes(){return Math.round(S.history.length*1.25);}
function stats(){const reviewed=[...S.progress.values()].filter(p=>p.reviews>0);const mastered=reviewed.filter(p=>p.mastery>=80).length;const today=dayKey(new Date());const todayN=S.history.filter(h=>h.ts&&dayKey(new Date(h.ts))===today).length;const days=new Set(S.history.map(h=>h.ts&&dayKey(new Date(h.ts))).filter(Boolean)).size;return {studied:reviewed.length,mastered,today:todayN,streak:streak(),minutes:totalStudyMinutes(),avg:days?Math.round(S.history.length/days):0};}
function highYield(q){return q.interviewFrequency>=4;}
function core(q){return q.interviewFrequency===5 && (q.difficulty<=4 || q.tags?.includes('interview-trap'));}
function getMode(mode,count=20,topic=''){
  let pool=[];
  if(mode==='daily'){pool=[...due(),...shuffled(unseen()).slice(0,S.settings.newPerDay)];}
  else if(mode==='random')pool=shuffled(BANK);
  else if(mode==='weak')pool=weakQuestions();
  else if(mode==='high')pool=shuffled(BANK.filter(highYield));
  else if(mode==='formula')pool=shuffled(BANK.filter(q=>q.formula));
  else if(mode==='calc')pool=shuffled(BANK.filter(q=>['Calculation','Mental Math','Mini-Case'].includes(q.questionType)));
  else if(mode==='core')pool=shuffled(BANK.filter(core));
  else if(mode==='bookmarks')pool=shuffled(BANK.filter(q=>prog(q.id).bookmarked));
  else if(mode==='ma')pool=shuffled(BANK.filter(q=>q.category==='M&A'));
  else if(mode==='accounting')pool=shuffled(BANK.filter(q=>q.category==='Accounting'));
  else if(mode==='valuation')pool=shuffled(BANK.filter(q=>q.category==='Valuation'));
  else if(mode==='markets')pool=shuffled(BANK.filter(q=>['Global Markets / Macro','Fixed Income / Derivatives'].includes(q.category)));
  else if(mode==='macro')pool=shuffled(BANK.filter(q=>q.category==='Global Markets / Macro'&&/macro|monetary|market reaction|international|fiscal/i.test(q.subcategory+' '+q.topic)));
  else if(mode==='topic')pool=shuffled(BANK.filter(q=>q.category===topic||q.subcategory===topic));
  else pool=shuffled(BANK);
  // Within practice modes, due/low-mastery items float upward without destroying randomness.
  pool=pool.map(q=>({q,key:(prog(q.id).reviews?0:1)+(prog(q.id).mastery||0)/100+Math.random()*.35})).sort((a,b)=>a.key-b.key).map(x=>x.q);
  return pool.slice(0,Math.min(count||20,pool.length));
}
function startSession(mode,count=20,topic=''){let qs=getMode(mode,count,topic);if(!qs.length){toast('No questions available for this mode yet.');return;}S.session={mode,qs,index:0,revealed:false,ratings:{},started:Date.now(),interview:false};S.view='study';render();}
function interviewPool(type,minutes){const n=Math.max(5,Math.ceil(minutes/2.3));let weights;
  if(type==='M&A Interview')weights=[['Accounting',.18],['Valuation',.24],['M&A',.48],['Mental Math',.10]];
  else if(type==='Investment Banking Interview')weights=[['Accounting',.23],['Valuation',.28],['M&A',.28],['Corporate Finance',.10],['Mental Math',.11]];
  else if(type==='Global Markets Interview')weights=[['Global Markets / Macro',.48],['Fixed Income / Derivatives',.28],['LBO / Credit',.10],['Mental Math',.14]];
  else weights=[['Accounting',.15],['Valuation',.18],['M&A',.24],['Global Markets / Macro',.18],['Fixed Income / Derivatives',.10],['Corporate Finance',.07],['Mental Math',.08]];
  const out=[];for(const [cat,w] of weights){const k=Math.max(1,Math.round(n*w));const p=shuffled(BANK.filter(q=>q.category===cat&&q.interviewFrequency>=4&&q.difficulty>=2));out.push(...p.slice(0,k));}
  return shuffled(out).slice(0,n);
}
function startInterview(type,minutes){const qs=interviewPool(type,minutes);S.session={mode:type,qs,index:0,revealed:false,ratings:{},started:Date.now(),interview:true,duration:minutes*60};S.view='study';render();}
function nextQuestion(){if(!S.session)return;S.session.index++;S.session.revealed=false;if(S.session.index>=S.session.qs.length){S.view='summary';}render();window.scrollTo(0,0);}
function reveal(){if(S.session){S.session.revealed=true;render();}}
function jumpQuestion(id){const q=byId.get(id);if(!q)return;S.session={mode:'Search',qs:[q],index:0,revealed:false,ratings:{},started:Date.now(),interview:false};S.view='study';render();}

// ---------- rendering ----------
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function stars(n){return '★'.repeat(n)+'☆'.repeat(Math.max(0,5-n));}
function shell(content,active='home'){return `<main class="app-shell"><div class="topbar"><div><div class="brand">CIB INTERVIEW DRILL</div><div class="subtle">${BANK.length.toLocaleString()} substantive questions · offline-first</div></div><button class="icon-btn" data-action="theme" aria-label="Toggle theme">◐</button></div>${content}</main>${nav(active)}`;}
function nav(active){const items=[['home','⌂','Today'],['search','⌕','Search'],['formulas','ƒx','Formulas'],['progress','◫','Progress'],['settings','⚙','Settings']];return `<nav class="nav">${items.map(([v,i,l])=>`<button data-view="${v}" class="${active===v?'active':''}"><span class="nav-icon">${i}</span>${l}</button>`).join('')}</nav>`;}
function home(){const st=stats(),d=due().length,n=unseen().length,weak=topicStats().slice(0,5);const modes=[['daily','Daily Review',`${d} due + up to ${Math.min(S.settings.newPerDay,n)} new`],['quick5','Quick 5','Five fast questions'],['quick10','Quick 10','Ten-question sprint'],['quick20','Quick 20','Focused practice'],['quick30','Quick 30','Longer recall set'],['quick50','Quick 50','Deep practice block'],['random','Random','Adaptive random mix'],['high','High-Yield','4–5 star questions'],['weak','Weak Areas','Adaptive by mastery'],['core','Core Interview','Must-answer questions'],['formula','Formulas Only','Formula recall cards'],['calc','Calculations','Cases & mental math'],['bookmarks','Bookmarked','Saved questions'],['ma','M&A Only','Priority category'],['accounting','Accounting','Three statements & mechanics'],['valuation','Valuation','DCF, comps & bridges'],['markets','Markets','Rates, FX, FI & derivatives'],['macro','Macro Only','Policy & cross-asset transmission']];return shell(`
<section class="card hero"><div class="eyebrow">Today</div><h1>${d} reviews due</h1><p class="subtle">${Math.min(S.settings.newPerDay,n)} new questions ready · ${st.streak} day streak</p><button class="btn accent full" data-start="daily" data-count="${Math.max(10,d+Math.min(S.settings.newPerDay,n))}">START DAILY SESSION</button></section>
<div class="grid three" style="margin-top:12px"><div class="card stat"><span class="subtle">Studied</span><b>${st.studied}</b></div><div class="card stat"><span class="subtle">Mastered</span><b>${st.mastered}</b></div><div class="card stat"><span class="subtle">Today</span><b>${st.today}</b></div></div>
<h2 class="section-title">Weak topics</h2><div class="weak-list">${weak.length?weak.map(x=>`<button class="chip" data-topic="${esc(x.name)}">${esc(x.name)} · ${x.mastery}%</button>`).join(''):'<span class="subtle">Study a few questions and weak areas will appear here.</span>'}</div>
<h2 class="section-title">Quick practice</h2><div class="mode-grid">${modes.map(([m,l,s])=>`<button class="mode-card" data-start="${m.startsWith('quick')?'random':m}" data-count="${m.startsWith('quick')?m.replace('quick',''):20}"><b>${l}</b><span>${s}</span></button>`).join('')}</div>
<h2 class="section-title">By topic</h2><section class="card"><div class="form-row"><label>Category</label><select id="topic-select"><option value="">Choose a category…</option>${[...new Set(BANK.map(q=>q.category))].map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><button class="btn full" data-action="start-topic">START TOPIC PRACTICE</button></section><h2 class="section-title">Interview mode</h2><section class="card"><div class="form-row"><label>Interview</label><select id="interview-type">${['M&A Interview','Investment Banking Interview','Global Markets Interview','Mixed CIB Interview'].map(x=>`<option ${x===S.settings.interviewType?'selected':''}>${x}</option>`).join('')}</select></div><div class="pill-row">${[10,20,30,45,60].map(x=>`<button class="chip ${x===S.settings.interviewMinutes?'active':''}" data-interview-min="${x}">${x} min</button>`).join('')}</div><button class="btn primary full" style="margin-top:14px" data-action="start-interview">START INTERVIEW</button></section>
`, 'home');}
function study(){const ss=S.session;if(!ss||ss.index>=ss.qs.length){S.view='home';return home();}const q=ss.qs[ss.index],p=prog(q.id),note=S.notes.get(q.id)||'';const pct=Math.round((ss.index/ss.qs.length)*100);return `<main class="app-shell"><div class="session-head"><button class="btn ghost" data-action="exit">← Exit</button><div class="session-count">${ss.index+1} / ${ss.qs.length}</div>${ss.interview?`<div class="interview-timer" id="timer">${fmtTime(Math.max(0,ss.duration-Math.floor((Date.now()-ss.started)/1000)))}</div>`:'<span></span>'}</div><div class="progressbar"><i style="width:${pct}%"></i></div><section class="card" style="margin-top:14px" id="question-card"><div class="qmeta"><span class="badge">${esc(q.category)} › ${esc(q.subcategory)}</span><span class="badge">${stars(q.interviewFrequency)}</span><span class="badge">LEVEL ${q.difficulty}</span><span class="badge">${esc(q.questionType)}</span></div><button class="star ${p.bookmarked?'on':''}" data-action="bookmark" aria-label="Bookmark">${p.bookmarked?'★':'☆'}</button><h1 class="question">${esc(q.question)}</h1>${!ss.revealed?`<button class="btn accent full" data-action="reveal">SHOW ANSWER / GIVE UP</button>`:answerBlock(q,note)} </section>${ss.revealed?`<div class="rating-row"><button class="rating again" data-rate="again">AGAIN</button><button class="rating hard" data-rate="hard">HARD</button><button class="rating good" data-rate="good">GOOD</button><button class="rating easy" data-rate="easy">EASY</button></div>`:''}</main>`;}
function answerBlock(q,note){return `<div class="answer"><h3>Ideal interview answer</h3><p>${esc(q.idealInterviewAnswer)}</p>${q.deepExplanation?`<h3>Deep explanation</h3><p>${esc(q.deepExplanation)}</p>`:''}${q.intuition?`<h3>Intuition / why</h3><p>${esc(q.intuition)}</p>`:''}${q.formula?`<h3>Formula</h3><div class="formula">${esc(q.formula)}</div>`:''}${q.variables?`<h3>Variables</h3><p>${esc(q.variables)}</p>`:''}${q.workedExample?`<h3>Worked example</h3><p>${esc(q.workedExample)}</p>`:''}${q.commonMistake?`<h3>Common mistake</h3><p>${esc(q.commonMistake)}</p>`:''}${q.interviewerTrap?`<h3>Interview trap</h3><p class="trap">${esc(q.interviewerTrap)}</p>`:''}${q.followUps?.length?`<h3>Follow-ups</h3><ul class="summary-list">${q.followUps.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<details><summary class="btn" style="margin-top:16px">EXPLAIN IN SPANISH</summary><p class="spanish" style="margin-top:12px">${esc(q.spanishExplanation||'')}</p></details><div class="form-row"><label>Personal note</label><textarea id="note" data-id="${esc(q.id)}" placeholder="Write a note for future reviews…">${esc(note)}</textarea></div></div>`;}
function searchView(){const cats=[...new Set(BANK.map(q=>q.category))];let r=[];if(S.query.trim().length>=2){const terms=S.query.toLowerCase().split(/\s+/).filter(Boolean);r=BANK.filter(q=>{const hay=[q.question,q.topic,q.subcategory,q.category,q.idealInterviewAnswer,q.formula,...(q.relatedConcepts||[])].join(' ').toLowerCase();return terms.every(t=>hay.includes(t));}).slice(0,80);}return shell(`<input class="search" id="search" placeholder="Search Sortino, Fed Funds, Goodwill, WACC…" value="${esc(S.query)}" autofocus><div class="pill-row" style="margin-top:10px">${cats.map(c=>`<button class="chip" data-search-cat="${esc(c)}">${esc(c)}</button>`).join('')}</div><section class="card" style="margin-top:12px">${S.query.trim().length<2?'<div class="empty">Type at least 2 characters.</div>':r.length?r.map(q=>`<div class="result"><button data-jump="${q.id}"><b>${esc(q.question)}</b><span>${esc(q.category)} › ${esc(q.subcategory)} · Level ${q.difficulty}${q.formula?` · ${esc(q.formula)}`:''}${q.relatedConcepts?.length?` · Related: ${esc(q.relatedConcepts.slice(0,3).join(', '))}`:''}</span></button></div>`).join(''):'<div class="empty">No matching questions.</div>'}</section>`,'search');}
function formulasView(){const term=S.formulaQuery.toLowerCase();const f=FORMULAS.filter(x=>!term||[x.topic,x.category,x.formula].join(' ').toLowerCase().includes(term)).slice(0,200);return shell(`<input class="search" id="formula-search" placeholder="Search formulas…" value="${esc(S.formulaQuery)}"><section class="grid" style="margin-top:12px">${f.map(x=>`<article class="card"><div class="eyebrow">${esc(x.category)}</div><h3>${esc(x.topic)}</h3><div class="formula">${esc(x.formula)}</div><h4>Interpretation</h4><p class="subtle">${esc(x.interpretation)}</p><h4>When used</h4><p class="subtle">${esc(x.whenUsed)}</p><h4>Variables</h4><p class="subtle">${esc(x.variables||'Use the variables and units shown in the formula; keep numerator and denominator definitions consistent.')}</p><details><summary>Common mistake</summary><p>${esc(x.commonMistake||'')}</p></details></article>`).join('')}</section>`,'formulas');}
function progressView(){const st=stats(),topics=topicStats().slice(0,25);const recent=[...S.history].reverse().filter(x=>['again','hard'].includes(x.rating)).slice(0,10);return shell(`<div class="grid two"><div class="card stat"><span class="subtle">Questions studied</span><b>${st.studied}</b></div><div class="card stat"><span class="subtle">Questions mastered</span><b>${st.mastered}</b></div><div class="card stat"><span class="subtle">Reviews today</span><b>${st.today}</b></div><div class="card stat"><span class="subtle">Current streak</span><b>${st.streak}</b></div><div class="card stat"><span class="subtle">Study time</span><b>${st.minutes}m</b></div><div class="card stat"><span class="subtle">Avg daily</span><b>${st.avg}</b></div></div><h2 class="section-title">Topic mastery</h2><section class="card">${topics.length?topics.map(x=>`<div class="topic-row"><div class="name">${esc(x.name)}</div><div class="bar"><i style="width:${x.mastery}%"></i></div><div class="pct">${x.mastery}%</div></div>`).join(''):'<div class="empty">Your mastery dashboard will populate as you study.</div>'}</section><h2 class="section-title">Recent mistakes</h2><section class="card">${recent.length?recent.map(h=>{const q=byId.get(h.id);return q?`<div class="result"><button data-jump="${q.id}"><b>${esc(q.question)}</b><span>${esc(h.rating.toUpperCase())} · ${esc(q.subcategory)}</span></button></div>`:''}).join(''):'<div class="empty">No recent Again/Hard ratings.</div>'}</section>`,'progress');}
function settingsView(){return shell(`<section class="card"><h2>Study settings</h2><div class="form-row"><label>Daily goal</label><select id="daily-goal">${[10,20,30,50,75,100].map(x=>`<option value="${x}" ${x===S.settings.dailyGoal?'selected':''}>${x} questions/day</option>`).join('')}</select></div><div class="form-row"><label>New questions in daily session</label><select id="new-day">${[5,10,15,20,30,50].map(x=>`<option value="${x}" ${x===S.settings.newPerDay?'selected':''}>${x}</option>`).join('')}</select></div><div class="form-row"><label>Theme</label><select id="theme">${['system','light','dark'].map(x=>`<option value="${x}" ${x===S.settings.theme?'selected':''}>${x}</option>`).join('')}</select></div></section><h2 class="section-title">Data</h2><section class="card"><button class="btn full" data-action="export">EXPORT BACKUP</button><label class="btn full" style="display:block;text-align:center;margin-top:10px">IMPORT BACKUP<input id="import" type="file" accept="application/json" hidden></label><button class="btn danger full" style="margin-top:10px" data-action="reset">RESET PROGRESS</button><p class="subtle">Backup includes progress, review history, bookmarks, notes, settings and study dates.</p></section><h2 class="section-title">Offline</h2><section class="card"><p>Once loaded, the core bank and app shell are cached for offline study. Add this site to your iPhone Home Screen from Safari for standalone use.</p><p class="subtle">SRS engine: local stability/difficulty scheduling inspired by modern spaced-repetition principles. No server or paid AI API is required.</p></section>`,'settings');}
function summaryView(){const ss=S.session||{ratings:{},qs:[]};const missed=ss.qs.filter(q=>['again','hard'].includes(ss.ratings[q.id]));const topics=[...new Set(missed.map(q=>q.subcategory))];const elapsed=Math.round((Date.now()-ss.started)/60000);return shell(`<section class="card hero"><div class="eyebrow">Session complete</div><h1>${ss.qs.length} questions</h1><p class="subtle">${elapsed} min · ${missed.length} marked Again/Hard</p><button class="btn accent full" data-view="home">BACK TO TODAY</button></section><h2 class="section-title">Topics missed</h2><section class="card">${topics.length?`<ul class="summary-list">${topics.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>No weak ratings this session.</p>'}</section><h2 class="section-title">Questions to review</h2><section class="card">${missed.length?missed.map(q=>`<div class="result"><button data-jump="${q.id}"><b>${esc(q.question)}</b><span>${esc(ss.ratings[q.id].toUpperCase())} · ${esc(q.subcategory)}</span></button></div>`).join(''):'<div class="empty">Strong session.</div>'}</section>`,'home');}
function render(){let html;if(S.view==='home')html=home();else if(S.view==='study')html=study();else if(S.view==='search')html=searchView();else if(S.view==='formulas')html=formulasView();else if(S.view==='progress')html=progressView();else if(S.view==='settings')html=settingsView();else if(S.view==='summary')html=summaryView();else html=home();app.outerHTML?document.getElementById('app').innerHTML=html:app.innerHTML=html;wireTimer();}
function fmtTime(s){const m=Math.floor(s/60),r=s%60;return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`;}
let timerInt;function wireTimer(){clearInterval(timerInt);if(S.view==='study'&&S.session?.interview){timerInt=setInterval(()=>{const el=document.getElementById('timer');if(!el)return;const left=Math.max(0,S.session.duration-Math.floor((Date.now()-S.session.started)/1000));el.textContent=fmtTime(left);},1000);}}
function toast(msg){const x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),1800);}
function applyTheme(){const t=S.settings.theme;document.documentElement.dataset.theme=t==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):t;}
function cycleTheme(){S.settings.theme=S.settings.theme==='light'?'dark':S.settings.theme==='dark'?'system':'light';saveSettings();render();toast(`Theme: ${S.settings.theme}`);}

// ---------- backup ----------
async function exportBackup(){const payload={version:1,exportedAt:new Date().toISOString(),bankQuestions:BANK.length,progress:[...S.progress.values()],notes:[...S.notes].map(([id,text])=>({id,text})),history:S.history,settings:S.settings,studyDays:JSON.parse(localStorage.getItem('cib-study-days')||'[]')};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cib-drill-backup-${dayKey(new Date())}.json`;a.click();URL.revokeObjectURL(a.href);}
async function importBackup(file){try{const x=JSON.parse(await file.text());if(x.version!==1||!Array.isArray(x.progress)||!Array.isArray(x.history))throw new Error('Invalid backup');await clearStore('progress');await clearStore('notes');await clearStore('history');S.progress.clear();S.notes.clear();S.history=[];for(const p of x.progress){S.progress.set(p.id,p);await put('progress',p);}for(const n of x.notes||[]){S.notes.set(n.id,n.text||'');await put('notes',n);}for(const h of x.history){S.history.push(h);await add('history',h);}S.settings={...DEFAULTS,...(x.settings||{})};saveSettings();localStorage.setItem('cib-study-days',JSON.stringify(x.studyDays||[]));render();toast('Backup restored');}catch(e){toast('Could not import backup');}}
async function resetAll(){if(!confirm('Reset all study progress, bookmarks, notes and review history? This cannot be undone unless you exported a backup.'))return;await Promise.all([clearStore('progress'),clearStore('notes'),clearStore('history')]);S.progress.clear();S.notes.clear();S.history=[];localStorage.removeItem('cib-study-days');render();toast('Progress reset');}

// ---------- events ----------
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-action],[data-view],[data-start],[data-topic],[data-jump],[data-interview-min]');if(!b)return;if(b.dataset.view){S.view=b.dataset.view;S.session=null;render();window.scrollTo(0,0);return;}if(b.dataset.start){startSession(b.dataset.start,Number(b.dataset.count)||20);return;}if(b.dataset.topic){startSession('topic',20,b.dataset.topic);return;}if(b.dataset.jump){jumpQuestion(b.dataset.jump);return;}if(b.dataset.rate){rate(S.session.qs[S.session.index].id,b.dataset.rate);return;}if(b.dataset.interviewMin){S.settings.interviewMinutes=Number(b.dataset.interviewMin);saveSettings();render();return;}const a=b.dataset.action;if(a==='theme')cycleTheme();if(a==='reveal')reveal();if(a==='exit'){S.session=null;S.view='home';render();}if(a==='bookmark'){const id=S.session.qs[S.session.index].id,p={...prog(id),bookmarked:!prog(id).bookmarked};S.progress.set(id,p);put('progress',p);render();}if(a==='start-topic'){const sel=document.getElementById('topic-select');if(sel?.value)startSession('topic',30,sel.value);else toast('Choose a category first.');}if(a==='start-interview'){const sel=document.getElementById('interview-type');S.settings.interviewType=sel?.value||S.settings.interviewType;saveSettings();startInterview(S.settings.interviewType,S.settings.interviewMinutes);}if(a==='export')exportBackup();if(a==='reset')resetAll();});
document.addEventListener('input',e=>{if(e.target.id==='search'){S.query=e.target.value;clearTimeout(S.searchTimer);S.searchTimer=setTimeout(()=>render(),120);}if(e.target.id==='formula-search'){S.formulaQuery=e.target.value;clearTimeout(S.searchTimer);S.searchTimer=setTimeout(()=>render(),120);}if(e.target.id==='note'){const id=e.target.dataset.id,text=e.target.value;S.notes.set(id,text);clearTimeout(e.target._t);e.target._t=setTimeout(()=>put('notes',{id,text}),250);}});
document.addEventListener('change',e=>{if(e.target.id==='daily-goal'){S.settings.dailyGoal=Number(e.target.value);saveSettings();}if(e.target.id==='new-day'){S.settings.newPerDay=Number(e.target.value);saveSettings();}if(e.target.id==='theme'){S.settings.theme=e.target.value;saveSettings();render();}if(e.target.id==='interview-type'){S.settings.interviewType=e.target.value;saveSettings();}if(e.target.id==='import'&&e.target.files?.[0])importBackup(e.target.files[0]);});
// One-hand optional gestures, only after answer is revealed.
let tx=null;document.addEventListener('touchstart',e=>{if(S.view==='study'&&S.session?.revealed)tx=e.changedTouches[0].clientX;},{passive:true});document.addEventListener('touchend',e=>{if(tx==null||S.view!=='study'||!S.session?.revealed)return;const dx=e.changedTouches[0].clientX-tx;tx=null;if(Math.abs(dx)<90)return;rate(S.session.qs[S.session.index].id,dx>0?'good':'again');},{passive:true});

async function boot(){if(!BANK.length){app.innerHTML='<div class="empty">Question bank failed to load.</div>';return;}await load();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});}
boot().catch(err=>{console.error(err);app.innerHTML=`<div class="empty">Could not start the app: ${esc(err.message)}</div>`;});
})();
