(() => {
'use strict';

const CONCEPTS=window.CORE_CONCEPTS||[];
const CASES=window.CASE_QUESTIONS||[];
const conceptById=new Map(CONCEPTS.map(c=>[c.id,c]));
const conceptByTitle=new Map(CONCEPTS.map(c=>[norm(c.t),c]));

function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9%&+Δβσ]+/g,' ').trim();}
function cleanFormula(raw){raw=(raw||'').trim();if(/^(no formula|no single formula|n\/a|none)$/i.test(raw))return '';return /[=≈≠\/×+−→↑↓<>%]/.test(raw)?raw:'';}
function expandConcept(c){
  const t=c.t,f=c.f,base=c.id,formula=cleanFormula(c.formula),rel=c.related||[];
  const ctx=`Key caveat: ${c.caveat} ${rel.length?`Useful cross-checks: ${rel.slice(0,4).join(', ')}.`:''}`;
  return [
    {id:`${base}-L1`,conceptId:base,category:c.cat,subcategory:c.sub,topic:t,difficulty:1,interviewFrequency:f,questionType:'Definition',question:`What is ${t}?`,idealInterviewAnswer:c.d,additionalContext:ctx,spanishExplanation:c.es,formula,variables:'',workedExample:'',commonMistake:c.caveat,interviewerTrap:c.trap_q,followUps:[`How does ${t} work mechanically?`,`Why does ${t} matter?`],relatedConcepts:rel,tags:[c.cat,c.sub,t,'foundation']},
    {id:`${base}-L2`,conceptId:base,category:c.cat,subcategory:c.sub,topic:t,difficulty:2,interviewFrequency:f,questionType:formula?'Formula Recall':'Explain Like an Analyst',question:`How does ${t} work mechanically, and how would you calculate or derive it?`,idealInterviewAnswer:`${formula?`Use ${formula}. `:''}${c.d}`,additionalContext:`What matters economically: ${c.why} Main caveat: ${c.caveat}`,spanishExplanation:c.es,formula,variables:'',workedExample:'',commonMistake:c.caveat,interviewerTrap:c.trap_q,followUps:[`Why does ${t} work?`,`What can make ${t} misleading?`],relatedConcepts:rel,tags:[c.cat,c.sub,t,'mechanics']},
    {id:`${base}-L3`,conceptId:base,category:c.cat,subcategory:c.sub,topic:t,difficulty:3,interviewFrequency:f,questionType:'Intuition',question:`Why does ${t} matter, and when is it useful in CIB?`,idealInterviewAnswer:c.why,additionalContext:`Use it only when the analytical question matches what it measures. Main caveat: ${c.caveat}${rel.length?` Cross-check with ${rel.slice(0,4).join(', ')}.`:''}`,spanishExplanation:c.es,formula,variables:'',workedExample:'',commonMistake:c.caveat,interviewerTrap:c.trap_q,followUps:[`What are the limitations of ${t}?`,c.trap_q],relatedConcepts:rel,tags:[c.cat,c.sub,t,'intuition']},
    {id:`${base}-L4`,conceptId:base,category:c.cat,subcategory:c.sub,topic:t,difficulty:4,interviewFrequency:Math.max(3,f-1),questionType:'Advanced Technical',question:`What are the main limitations, caveats or ways ${t} can mislead you?`,idealInterviewAnswer:c.caveat,additionalContext:`A strong answer should state what you would cross-check before relying on this metric or concept${rel.length?`: ${rel.slice(0,4).join(', ')}`:'.'} The correct interpretation depends on the business model, accounting and decision context.`,spanishExplanation:c.es,formula,variables:'',workedExample:'',commonMistake:`Using ${t} in isolation without checking the underlying economics.`,interviewerTrap:c.trap_q,followUps:[c.trap_q,`What would you cross-check before relying on ${t}?`],relatedConcepts:rel,tags:[c.cat,c.sub,t,'limitations']},
    {id:`${base}-L5`,conceptId:base,category:c.cat,subcategory:c.sub,topic:t,difficulty:5,interviewFrequency:f,questionType:'Trick Question',question:c.trap_q,idealInterviewAnswer:c.trap_a,additionalContext:`This tests whether you can avoid a mechanical rule and explain the underlying economics. Key caveat: ${c.caveat}`,spanishExplanation:c.es,formula,variables:'',workedExample:'',commonMistake:`Giving a one-line rule without testing the assumptions behind ${t}.`,interviewerTrap:'⚠ INTERVIEW TRAP',followUps:[`How would you test that conclusion quantitatively?`,`What assumption could make the opposite conclusion reasonable?`],relatedConcepts:rel,tags:[c.cat,c.sub,t,'interview-trap']}
  ];
}
function caseContext(q){
  const parts=[];
  const d=String(q.deepExplanation||'').trim();
  const a=String(q.idealInterviewAnswer||'').trim();
  if(d && norm(d)!==norm(a) && !norm(d).startsWith(norm(a))) parts.push(d);
  if(q.intuition && !parts.some(x=>norm(x).includes(norm(q.intuition)))) parts.push(q.intuition);
  if(!parts.length && q.commonMistake) parts.push(`Cross-check the assumptions before calculating. ${q.commonMistake}`);
  return parts.join(' ');
}
const BANK=[...CONCEPTS.flatMap(expandConcept),...CASES.map(q=>({...q,additionalContext:caseContext(q)}))]
  .map(q=>({...q,formula:cleanFormula(q.formula),collection:(q.interviewFrequency===5&&(q.difficulty<=4||q.tags?.includes('interview-trap')))?'Core Interview Questions':(q.collection||'Evergreen Technical')}));
const byId=new Map(BANK.map(q=>[q.id,q]));
const FORMULAS=(()=>{const m=new Map();for(const q of BANK){if(!q.formula)continue;const k=`${q.topic}|${q.formula}`;if(!m.has(k))m.set(k,{topic:q.topic,category:q.category,formula:q.formula,variables:q.variables||'',interpretation:q.additionalContext||q.spanishExplanation||'',whenUsed:q.idealInterviewAnswer||'',commonMistake:q.commonMistake||''});}return [...m.values()];})();

const MANUAL_GLOSSARY=[
  {term:'PIK interest',aliases:['payment in kind','pik'],en:'Payment-in-kind interest is not paid in cash today; it is capitalised into the debt principal and therefore increases the amount owed.',es:'PIK (payment-in-kind) es interés que no se paga en caja hoy: se capitaliza y se suma al principal de la deuda, por lo que la deuda crece.'},
  {term:'Enterprise Value (EV)',aliases:['enterprise value','ev'],en:'Enterprise value measures the value of the operating business attributable to all capital providers, before allocating value between debt and equity.',es:'Enterprise Value (EV) mide el valor del negocio operativo para todos los proveedores de capital, antes de repartir ese valor entre deuda y equity.'},
  {term:'Equity Value',aliases:['equity value','market cap','market capitalization'],en:'Equity value is the value attributable to common shareholders. For a public company, market capitalisation is share price multiplied by basic shares outstanding.',es:'Equity Value es el valor atribuible a los accionistas comunes. En una empresa cotizada, market cap es precio por acción multiplicado por acciones básicas en circulación.'},
  {term:'Accretion / dilution',aliases:['accretion','dilution','accretive','dilutive'],en:'Accretion/dilution measures whether a transaction increases or decreases the buyer’s pro forma EPS. It is not the same as value creation.',es:'Accretion/dilution mide si una transacción aumenta o reduce el EPS pro forma del comprador. No es lo mismo que creación de valor.'},
  {term:'Purchase Price Allocation (PPA)',aliases:['ppa','purchase accounting'],en:'PPA allocates acquisition consideration to the fair value of identifiable assets and liabilities; residual value generally becomes goodwill.',es:'Purchase Price Allocation (PPA) distribuye el precio de adquisición al fair value de activos y pasivos identificables; el residual normalmente se registra como goodwill.'},
  {term:'Goodwill',aliases:['goodwill'],en:'Goodwill is the residual acquisition value after recognised identifiable net assets are measured at fair value, subject to the accounting framework.',es:'Goodwill es el valor residual de una adquisición después de reconocer a fair value los activos y pasivos netos identificables.'},
  {term:'Net Debt',aliases:['net debt'],en:'Net debt is generally gross debt less cash and cash equivalents, with exact transaction definitions depending on the context.',es:'Net Debt es, en términos generales, deuda bruta menos caja y equivalentes; la definición exacta depende del contexto de la transacción.'},
  {term:'NCI',aliases:['nci','non-controlling interest','minority interest'],en:'Non-controlling interest is the portion of a consolidated subsidiary that is owned by shareholders other than the parent.',es:'NCI (non-controlling interest) es la parte de una subsidiaria consolidada que pertenece a accionistas distintos de la matriz.'},
  {term:'NOPAT',aliases:['nopat'],en:'NOPAT is net operating profit after tax: operating profit after applying taxes, before financing effects.',es:'NOPAT es el beneficio operativo después de impuestos, antes de efectos de financiación.'},
  {term:'UFCF / FCFF',aliases:['ufcf','fcff','unlevered free cash flow'],en:'Unlevered free cash flow is cash flow available to all capital providers before interest and net borrowing.',es:'UFCF o FCFF es el flujo de caja disponible para todos los proveedores de capital antes de intereses y financiación neta.'},
  {term:'FCFE',aliases:['fcfe','levered free cash flow'],en:'Free cash flow to equity is cash flow available to common equity holders after debt-related cash flows.',es:'FCFE es el flujo de caja disponible para los accionistas después de considerar los flujos relacionados con deuda.'},
  {term:'WACC',aliases:['wacc'],en:'WACC is the weighted average required return of debt and equity capital, adjusted for the tax effect of debt where appropriate.',es:'WACC es el coste promedio ponderado exigido por deuda y equity, ajustando el efecto fiscal de la deuda cuando corresponde.'},
  {term:'Basis point (bp/bps)',aliases:['basis point','bps',' bp ',' bp.'],en:'One basis point is 0.01 percentage points. 100 bps equals 1.00 percentage point.',es:'Un basis point (bp) equivale a 0,01 puntos porcentuales. 100 bps equivalen a 1,00 punto porcentual.'},
  {term:'Duration',aliases:['duration','modified duration'],en:'Duration measures a bond’s sensitivity to interest-rate changes; modified duration approximates the percentage price change for a small change in yield.',es:'Duration mide la sensibilidad del precio de un bono a cambios de tasas; modified duration aproxima el cambio porcentual del precio ante un pequeño cambio de yield.'},
  {term:'Convexity',aliases:['convexity'],en:'Convexity captures the curvature in the price-yield relationship and improves the duration approximation for larger yield moves.',es:'Convexity captura la curvatura de la relación precio-yield y mejora la aproximación de duration para movimientos de tasas mayores.'},
  {term:'Clean / dirty price',aliases:['clean price','dirty price','accrued interest'],en:'Clean price excludes accrued interest. Dirty price is the actual settlement price and equals clean price plus accrued interest.',es:'Clean price excluye accrued interest. Dirty price es el precio efectivo de liquidación: clean price más accrued interest.'},
  {term:'ITM / ATM / OTM',aliases:['itm','atm','otm','in the money','at the money','out of the money'],en:'Moneyness compares an option’s strike with the underlying price: ITM has intrinsic value, ATM is near the strike, and OTM has no intrinsic value.',es:'Moneyness compara el strike de una opción con el precio del subyacente: ITM tiene valor intrínseco, ATM está cerca del strike y OTM no tiene valor intrínseco.'},
  {term:'CDS spread',aliases:['cds','credit default swap'],en:'A CDS spread is the periodic premium paid for credit protection; wider spreads generally indicate higher perceived credit risk, all else equal.',es:'El CDS spread es la prima periódica por protección crediticia; un spread más amplio suele indicar mayor riesgo de crédito percibido, ceteris paribus.'}
];
const AUTO_GLOSSARY=CONCEPTS.map(c=>({term:c.t,aliases:[c.t,...(c.related||[])],en:c.d,es:c.es}));
const GLOSSARY=[...MANUAL_GLOSSARY,...AUTO_GLOSSARY];

const UI={
  en:{today:'Today',search:'Search',formulas:'Formulas',progress:'Progress',settings:'Settings',offline:'offline-first',reviewsDue:'reviews due',newReady:'new questions ready',dayStreak:'day streak',startDaily:'START DAILY SESSION',studied:'Studied',mastered:'Mastered',todayCount:'Today',weakTopics:'Weak topics',quickPractice:'Quick practice',byTopic:'By topic',category:'Category',chooseCategory:'Choose a category…',startTopic:'START TOPIC PRACTICE',interviewMode:'Interview mode',interview:'Interview',startInterview:'START INTERVIEW',difficulty:'Difficulty',allLevels:'All levels',foundation:'Foundation',advanced:'Advanced',language:'Language',question:'Question',showAnswer:'SHOW ANSWER / GIVE UP',interviewResponse:'Interview response',definitions:'Definitions',additionalContext:'Additional context',formula:'Formula',variables:'Variables',workedExample:'Worked example',commonMistake:'Common mistake',interviewTrap:'Interview trap',followUps:'Follow-ups',personalNote:'Personal note',notePlaceholder:'Write a note for future reviews…',exit:'Exit',again:'AGAIN',hard:'HARD',good:'GOOD',easy:'EASY',typeSearch:'Search Sortino, Fed Funds, Goodwill, WACC…',typeTwo:'Type at least 2 characters.',noMatches:'No matching questions.',searchFormulas:'Search formulas…',interpretation:'Interpretation',whenUsed:'When used',data:'Data',studySettings:'Study settings',dailyGoal:'Daily goal',newQuestions:'New questions in daily session',theme:'Theme',exportBackup:'EXPORT BACKUP',importBackup:'IMPORT BACKUP',resetProgress:'RESET PROGRESS',sessionComplete:'Session complete',topicsMissed:'Topics missed',questionsReview:'Questions to review',backToday:'BACK TO TODAY',noWeak:'No weak ratings this session.',strongSession:'Strong session.',originalEnglish:'Original English',translationNote:'Technical interview terms are intentionally kept in English where that is the market-standard wording.',noQuestions:'No questions available for the selected difficulty.'},
  es:{today:'Hoy',search:'Buscar',formulas:'Fórmulas',progress:'Progreso',settings:'Ajustes',offline:'offline',reviewsDue:'repasos pendientes',newReady:'preguntas nuevas listas',dayStreak:'días de racha',startDaily:'EMPEZAR REPASO DIARIO',studied:'Estudiadas',mastered:'Dominadas',todayCount:'Hoy',weakTopics:'Temas débiles',quickPractice:'Práctica rápida',byTopic:'Por tema',category:'Categoría',chooseCategory:'Elige una categoría…',startTopic:'EMPEZAR PRÁCTICA POR TEMA',interviewMode:'Modo entrevista',interview:'Entrevista',startInterview:'EMPEZAR ENTREVISTA',difficulty:'Dificultad',allLevels:'Todas',foundation:'Base',advanced:'Avanzada',language:'Idioma',question:'Pregunta',showAnswer:'VER RESPUESTA / ME RINDO',interviewResponse:'Respuesta de entrevista',definitions:'Definiciones',additionalContext:'Información complementaria',formula:'Fórmula',variables:'Variables',workedExample:'Ejemplo resuelto',commonMistake:'Error común',interviewTrap:'Trampa de entrevista',followUps:'Preguntas de seguimiento',personalNote:'Nota personal',notePlaceholder:'Escribe una nota para repasos futuros…',exit:'Salir',again:'OTRA VEZ',hard:'DIFÍCIL',good:'BIEN',easy:'FÁCIL',typeSearch:'Busca Sortino, Fed Funds, Goodwill, WACC…',typeTwo:'Escribe al menos 2 caracteres.',noMatches:'No hay preguntas coincidentes.',searchFormulas:'Buscar fórmulas…',interpretation:'Interpretación',whenUsed:'Cuándo se usa',data:'Datos',studySettings:'Ajustes de estudio',dailyGoal:'Meta diaria',newQuestions:'Preguntas nuevas por sesión diaria',theme:'Tema visual',exportBackup:'EXPORTAR BACKUP',importBackup:'IMPORTAR BACKUP',resetProgress:'REINICIAR PROGRESO',sessionComplete:'Sesión completada',topicsMissed:'Temas a reforzar',questionsReview:'Preguntas para repasar',backToday:'VOLVER A HOY',noWeak:'No hubo respuestas Again/Hard en esta sesión.',strongSession:'Sesión sólida.',originalEnglish:'Original en inglés',translationNote:'Los términos técnicos de entrevista se mantienen en inglés cuando esa es la forma estándar del mercado.',noQuestions:'No hay preguntas para la dificultad seleccionada.'}
};
function t(k){return UI[S.settings.language]?.[k]||UI.en[k]||k;}

const PHRASES=[
 ['all else equal','manteniendo todo lo demás constante'],['what happens','qué sucede'],['what is the','cuál es el'],['what is','qué es'],['why might','por qué podría'],['why can','por qué puede'],['why does','por qué'],['walk me through','explícame paso a paso'],['walk through','explica paso a paso'],['assume a','supón una'],['assume no','supón que no hay'],['ignore fees','ignora las comisiones'],['ignore taxes','ignora los impuestos'],['ignore other items','ignora otros elementos'],['annual after-tax','anual después de impuestos'],['annual pre-tax','anual antes de impuestos'],['tax rate','tasa impositiva'],['share price','precio por acción'],['market value','valor de mercado'],['purchase price','precio de compra'],['purchase-accounting effects','efectos de purchase accounting'],['purchase accounting','purchase accounting'],['net income','utilidad neta'],['cash flow','flujo de caja'],['cash flows','flujos de caja'],['income statement','estado de resultados'],['balance sheet','balance general'],['cash flow statement','estado de flujo de caja'],['enterprise value','enterprise value'],['equity value','equity value'],['free cash flow','free cash flow'],['working capital','working capital'],['accounts receivable','accounts receivable'],['accounts payable','accounts payable'],['deferred revenue','deferred revenue'],['cost synergies','sinergias de costes'],['revenue synergy','sinergia de ingresos'],['interest expense','gasto por intereses'],['interest income','ingreso por intereses'],['debt principal','principal de la deuda'],['common equity','equity común'],['shares outstanding','acciones en circulación'],['new shares','acciones nuevas'],['offer premium','prima de la oferta'],['offer price','precio de oferta'],['unaffected share price','precio de la acción no afectado'],['after-tax earnings','beneficio después de impuestos'],['pre-tax income','beneficio antes de impuestos'],['first-pass','primera aproximación'],['all-stock','100% con acciones'],['entirely with stock','íntegramente con acciones'],['entirely in stock','íntegramente en acciones'],['entirely with cash','íntegramente con caja'],['what annual','qué importe anual'],['how many','cuántas'],['how much','cuánto'],['what direction','en qué dirección'],['what does that generally signal','qué suele señalar eso'],['give two plausible explanations','da dos explicaciones plausibles'],['balanced first-pass cross-asset reaction','reacción cross-asset equilibrada de primera aproximación'],['without inventing personal experiences','sin inventar experiencias personales'],['framework for','estructura para'],['give a strong framework for','da una estructura sólida para']
];
const WORDS={
  company:'empresa',buyer:'comprador',target:'target',deal:'operación',transaction:'transacción',cash:'caja',debt:'deuda',equity:'equity',revenue:'ingresos',expense:'gasto',expenses:'gastos',inventory:'inventario',customer:'cliente',service:'servicio',delivered:'prestado',borrows:'toma prestado',repays:'amortiza',issues:'emite',repurchases:'recompra',shares:'acciones',goodwill:'goodwill',impairment:'deterioro',interest:'interés',rate:'tasa',rates:'tasas',higher:'mayor',lower:'menor',rises:'sube',falls:'baja',increase:'aumento',increases:'aumenta',decreases:'disminuye',price:'precio',value:'valor',annual:'anual',recurring:'recurrente',premium:'prima',synergies:'sinergias',fees:'comisiones',earnings:'beneficio',contribution:'contribución',required:'requerido',created:'creado',creates:'crea',fair:'justo',identifiable:'identificables',asset:'activo',assets:'activos',liability:'pasivo',liabilities:'pasivos',funded:'financiado',funds:'financia',stock:'acciones',ownership:'participación',margin:'margen',growth:'crecimiento',return:'retorno',yield:'yield',bond:'bono',bonds:'bonos',duration:'duration',spread:'spread',default:'default',recovery:'recuperación',currency:'moneda',strengthens:'se fortalece',weakens:'se debilita',government:'gubernamental',selloff:'venta masiva',approximate:'aproximadamente',calculate:'calcula',defined:'definido',strong:'fuerte',wages:'salarios',unemployment:'desempleo',policy:'política',expectations:'expectativas',immediately:'inmediatamente',period:'periodo',current:'actual',future:'futuro',payment:'pago',paid:'pagado',sold:'vendido',recognised:'reconocido',recognized:'reconocido',held:'mantenido',constant:'constante',delayed:'retrasado',simplified:'simplificado',effect:'efecto',results:'resulta',result:'resultado',required:'necesario',combined:'combinado',fixed:'fijo',floating:'flotante',exposure:'exposición',natural:'natural',hedge:'cobertura',expected:'esperado',loss:'pérdida',risk:'riesgo',stronger:'más fuerte',weaker:'más débil',framework:'estructura',recent:'reciente',leadership:'liderazgo',conflict:'conflicto',failure:'fracaso',pressure:'presión'
};
function translateLoose(text){
  let s=String(text||''); if(!s)return s;
  for(const [a,b] of PHRASES)s=s.replace(new RegExp(a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi'),m=>matchCase(m,b));
  s=s.replace(/\b([A-Za-z][A-Za-z'-]*)\b/g,(m)=>{const r=WORDS[m.toLowerCase()];return r?matchCase(m,r):m;});
  s=s.replace(/\bIf\b/g,'Si').replace(/\bBecause\b/g,'Porque').replace(/\bNo\.\b/g,'No.').replace(/\bYes\.\b/g,'Sí.');
  return s;
}
function matchCase(src,dst){return /^[A-Z]/.test(src)?dst.charAt(0).toUpperCase()+dst.slice(1):dst;}
function coreLevel(q){const m=String(q.id).match(/-L([1-5])$/);return m?Number(m[1]):0;}
function questionText(q){
  if(S.settings.language!=='es')return q.question;
  const c=q.conceptId?conceptById.get(q.conceptId):null,l=coreLevel(q),topic=q.topic;
  if(c){
    if(l===1)return `¿Qué es ${topic}?`;
    if(l===2)return `¿Cómo funciona ${topic} mecánicamente y cómo lo calcularías o derivarías?`;
    if(l===3)return `¿Por qué importa ${topic} y cuándo es útil en CIB?`;
    if(l===4)return `¿Cuáles son las principales limitaciones, matices o formas en que ${topic} puede llevarte a una conclusión errónea?`;
  }
  return translateLoose(q.question);
}
function answerText(q){
  if(S.settings.language!=='es')return q.idealInterviewAnswer;
  const c=q.conceptId?conceptById.get(q.conceptId):null,l=coreLevel(q);
  if(c){
    if(l===1||l===3)return c.es;
    if(l===2)return `${q.formula?`Usa la relación mostrada en la fórmula. `:''}${c.es}`;
    if(l===4)return `Matiz clave: ${translateLoose(c.caveat)}`;
    if(l===5)return translateLoose(c.trap_a);
  }
  return translateLoose(q.idealInterviewAnswer);
}
function contextText(q){
  if(S.settings.language!=='es')return q.additionalContext||'';
  const c=q.conceptId?conceptById.get(q.conceptId):null;
  if(c){const rel=(c.related||[]).slice(0,4).join(', ');return `Matiz importante: ${translateLoose(c.caveat)}${rel?` Conéctalo con: ${rel}.`:''}`;}
  const exact=q.additionalContext?translateLoose(q.additionalContext):'';
  const support=q.spanishExplanation||'';
  if(exact&&support&&norm(exact)!==norm(support))return `${exact} ${support}`;
  return exact||support;
}
function localText(s){return S.settings.language==='es'?translateLoose(s):s;}

function definitionCandidates(q){
  const out=[];const seen=new Set();
  const add=g=>{if(!g||seen.has(norm(g.term))||out.length>=5)return;seen.add(norm(g.term));out.push(g);};
  if(q.conceptId){const c=conceptById.get(q.conceptId);if(c)add({term:c.t,en:c.d,es:c.es});}
  const targets=[q.topic,...(q.relatedConcepts||[])].filter(Boolean);
  for(const x of targets){const n=norm(x);const exact=conceptByTitle.get(n);if(exact)add({term:exact.t,en:exact.d,es:exact.es});for(const g of MANUAL_GLOSSARY){if(g.aliases.some(a=>n===norm(a)||n.includes(norm(a))||norm(a).includes(n)))add(g);}}
  const hay=norm([q.question,q.idealInterviewAnswer,q.formula,q.additionalContext].join(' '));
  for(const g of GLOSSARY){if(out.length>=5)break;const aliases=g.aliases||[g.term];if(aliases.some(a=>{const n=norm(a);return n.length>3&&hay.includes(n);})){add(g);}}
  if(!out.length){const cat={
    'Accounting':{term:'Accounting linkage',en:'Accounting links profitability, cash movement and the balance sheet; interview answers should keep recognition, cash timing and balance-sheet effects consistent.',es:'La contabilidad conecta rentabilidad, movimiento de caja y balance; en entrevista debes mantener consistentes reconocimiento, timing de caja y efectos en balance.'},
    'M&A':{term:'M&A mechanics',en:'M&A analysis separates valuation, purchase price, financing, purchase accounting, synergies and ownership effects.',es:'El análisis de M&A separa valoración, precio, financiación, purchase accounting, sinergias y efectos sobre la propiedad.'},
    'Valuation':{term:'Valuation',en:'Valuation estimates what a business or security is worth under a defined set of cash-flow, risk and market assumptions.',es:'Valuation estima cuánto vale un negocio o activo bajo supuestos definidos de cash flow, riesgo y mercado.'},
    'Mental Math':{term:'Interview mental math',en:'Mental-math questions test speed, structure and unit discipline more than calculator-level precision.',es:'El mental math de entrevista prueba velocidad, estructura y disciplina de unidades más que precisión de calculadora.'},
    'Behavioural':{term:'Interview framework',en:'A framework structures an answer; the evidence and examples must still come from the candidate’s real experience.',es:'Un framework estructura la respuesta; la evidencia y los ejemplos deben provenir de experiencias reales de la persona candidata.'},
    'LBO / Credit':{term:'Credit analysis',en:'Credit analysis focuses on a borrower’s ability to service debt, downside protection, leverage, liquidity and recovery if things go wrong.',es:'El análisis de crédito evalúa la capacidad de pagar deuda, la protección en downside, leverage, liquidez y recuperación si el escenario empeora.'},
    'Fixed Income / Derivatives':{term:'Fixed income / derivatives',en:'Fixed-income and derivative questions connect price, yield, rates, cash flows, risk sensitivities and hedging mechanics.',es:'Las preguntas de renta fija y derivados conectan precio, yield, tasas, cash flows, sensibilidades de riesgo y mecánica de cobertura.'},
    'Global Markets / Macro':{term:'Market transmission',en:'Market reactions depend on what was already priced, the source and size of the shock, positioning, policy expectations and the time horizon.',es:'Las reacciones de mercado dependen de lo que ya estaba priced, la causa y magnitud del shock, positioning, expectativas de política y horizonte temporal.'},
    'Corporate Finance':{term:'Corporate finance',en:'Corporate finance links investment decisions, capital structure, returns, cost of capital and value creation.',es:'Corporate finance conecta decisiones de inversión, estructura de capital, retornos, coste de capital y creación de valor.'},
    'Financial Ratios':{term:'Financial ratio',en:'A financial ratio compresses accounting or market information into a comparable metric; the numerator, denominator and business context must stay consistent.',es:'Un ratio financiero resume información contable o de mercado en una métrica comparable; numerador, denominador y contexto del negocio deben ser consistentes.'},
    'Banking / Capital Markets':{term:'Banking / capital markets',en:'Banking and capital-markets metrics link funding, capital, liquidity, credit risk, issuance and market intermediation.',es:'Las métricas de banca y mercados de capitales conectan funding, capital, liquidez, riesgo de crédito, emisión e intermediación de mercado.'}
  }[q.category];if(cat)add(cat);}
  return out;
}
function definitionsHTML(q){const defs=definitionCandidates(q);return `<div class="definition-grid">${defs.map(d=>`<div class="definition-item"><b>${esc(d.term)}</b><p>${esc(S.settings.language==='es'?(d.es||translateLoose(d.en)):d.en)}</p></div>`).join('')}</div>`;}

function mathHTML(formula){
  if(!formula)return '';
  return String(formula).split(/;|\n/).filter(Boolean).map(line=>`<div class="math-line">${mathLine(line.trim())}</div>`).join('');
}
function mathLine(s){
  let z=esc(s).replace(/\*+/g,'×');
  z=z.replace(/_\(([^)]+)\)/g,'<sub>$1</sub>').replace(/_([A-Za-z0-9]+)/g,'<sub>$1</sub>');
  z=z.replace(/\^\(([^)]+)\)/g,'<sup>($1)</sup>').replace(/\^([A-Za-z0-9.+−-]+)/g,'<sup>$1</sup>');
  z=z.replace(/-&gt;/g,'→').replace(/\bSigma\b/g,'Σ');
  const slashCount=(z.match(/\//g)||[]).length;
  if(slashCount===1){
    const ops=[' = ',' ≈ ',' ≠ '];let split=null;
    for(const op of ops){if(z.includes(op)){split=op;break;}}
    let prefix='',expr=z;if(split){const p=z.indexOf(split);prefix=z.slice(0,p+split.length);expr=z.slice(p+split.length);}
    const i=expr.indexOf('/'); if(i>-1){
      let num=expr.slice(0,i).trim(),rest=expr.slice(i+1).trim(),tail='';
      const tx=rest.search(/\s[×+−]\s/);if(tx>-1){tail=rest.slice(tx);rest=rest.slice(0,tx).trim();}
      if(num&&rest&&num.length<85&&rest.length<85)z=`${prefix}<span class="frac"><span>${num}</span><span>${rest}</span></span>${tail}`;
    }
  }
  return z;
}

const app=document.getElementById('app');
const DAY=86400000;
const DEFAULTS={theme:'system',dailyGoal:30,newPerDay:15,interviewType:'M&A Interview',interviewMinutes:20,language:'en',difficulty:'all'};
const S={view:'home',progress:new Map(),notes:new Map(),history:[],settings:{...DEFAULTS},session:null,query:'',formulaQuery:'',searchTimer:null};

// ---------- persistence ----------
function idb(){return new Promise((res,rej)=>{const r=indexedDB.open('CIBDrillDB',1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('progress'))d.createObjectStore('progress',{keyPath:'id'});if(!d.objectStoreNames.contains('notes'))d.createObjectStore('notes',{keyPath:'id'});if(!d.objectStoreNames.contains('history'))d.createObjectStore('history',{keyPath:'key',autoIncrement:true});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function getAll(store){const d=await idb();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);});}
async function put(store,val){const d=await idb();return new Promise((res,rej)=>{const r=d.transaction(store,'readwrite').objectStore(store).put(val);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function add(store,val){const d=await idb();return new Promise((res,rej)=>{const r=d.transaction(store,'readwrite').objectStore(store).add(val);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function clearStore(store){const d=await idb();return new Promise((res,rej)=>{const r=d.transaction(store,'readwrite').objectStore(store).clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}
async function load(){S.settings={...DEFAULTS,...JSON.parse(localStorage.getItem('cib-settings')||'{}')};(await getAll('progress')).forEach(x=>S.progress.set(x.id,x));(await getAll('notes')).forEach(x=>S.notes.set(x.id,x.text||''));S.history=await getAll('history');applyTheme();}
function saveSettings(){localStorage.setItem('cib-settings',JSON.stringify(S.settings));applyTheme();}
function baseProgress(id){return {id,reviews:0,ratingHistory:[],lastReview:null,nextReview:0,interval:0,difficulty:5,stability:.4,mastery:0,lapses:0,bookmarked:false};}
function prog(id){return S.progress.get(id)||baseProgress(id);}
function retrieval(p,now=Date.now()){if(!p.lastReview||!p.stability)return 1;const elapsed=Math.max(0,(now-new Date(p.lastReview).getTime())/DAY);return Math.exp(Math.log(.9)*elapsed/Math.max(.1,p.stability));}
function calcMastery(p){if(!p.reviews)return 0;const rs=p.ratingHistory.slice(-12);const perf=rs.reduce((a,r)=>a+({again:0,hard:.45,good:.78,easy:1}[r]??0),0)/Math.max(1,rs.length);const stab=Math.min(1,Math.log1p(p.stability)/Math.log(61));const ret=Math.min(1,retrieval(p));const diff=1-(p.difficulty-1)/9;const lapse=Math.max(0,1-p.lapses/Math.max(3,p.reviews));return Math.round(100*(.32*stab+.28*perf+.2*ret+.1*diff+.1*lapse));}
function schedule(prev,rating){const p={...baseProgress(prev.id),...prev};const now=Date.now();let d=p.difficulty||5,st=p.stability||.4,interval;if(rating==='again'){d=Math.min(10,d+1.2);st=Math.max(.12,st*.45);interval=Math.max(.02,Math.min(.25,st*.18));p.lapses=(p.lapses||0)+1;}if(rating==='hard'){d=Math.min(10,d+.35);st=Math.max(.35,st*1.28);interval=Math.max(.5,st*.85);}if(rating==='good'){d=Math.max(1,d-.2);st=Math.max(1,st*(1.7+.055*(10-d)));interval=Math.max(1,st);}if(rating==='easy'){d=Math.max(1,d-.7);st=Math.max(2,st*(2.35+.075*(10-d)));interval=Math.max(3,st*1.25);}p.reviews=(p.reviews||0)+1;p.ratingHistory=[...(p.ratingHistory||[]),rating].slice(-40);p.lastReview=new Date(now).toISOString();p.interval=Math.round(interval*100)/100;p.nextReview=now+interval*DAY;p.difficulty=Math.round(d*100)/100;p.stability=Math.round(st*100)/100;p.mastery=calcMastery(p);return p;}
async function rate(id,rating){const p=schedule(prog(id),rating);S.progress.set(id,p);await put('progress',p);const q=byId.get(id);const h={id,rating,ts:new Date().toISOString(),category:q?.category,topic:q?.topic,difficulty:q?.difficulty};S.history.push(h);await add('history',h);markStudyDay();if(S.session){S.session.ratings[id]=rating;if(rating==='again'){const x=byId.get(id);const insertAt=Math.min(S.session.qs.length,S.session.index+4);S.session.qs.splice(insertAt,0,x);}nextQuestion();}else render();}
function markStudyDay(){const today=dayKey(new Date());let d=JSON.parse(localStorage.getItem('cib-study-days')||'[]');if(!d.includes(today)){d.push(today);d=d.slice(-500);localStorage.setItem('cib-study-days',JSON.stringify(d));}}
function dayKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function streak(){const set=new Set(JSON.parse(localStorage.getItem('cib-study-days')||'[]'));let n=0,d=new Date();for(;;){if(set.has(dayKey(d)))n++;else break;d=new Date(d.getTime()-DAY);}return n;}

// ---------- queue / analytics ----------
function shuffled(xs){const a=[...xs];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function difficultyOK(q){return S.settings.difficulty==='all'||q.difficulty===Number(S.settings.difficulty);}
function due(){const now=Date.now();return BANK.filter(q=>difficultyOK(q)&&prog(q.id).reviews>0&&(prog(q.id).nextReview||0)<=now).sort((a,b)=>(prog(a.id).nextReview||0)-(prog(b.id).nextReview||0));}
function unseen(){return BANK.filter(q=>difficultyOK(q)&&!prog(q.id).reviews);}
function topicStats(){const m=new Map();for(const q of BANK.filter(difficultyOK)){const p=prog(q.id);if(!m.has(q.subcategory))m.set(q.subcategory,{n:0,sum:0,reviewed:0});const x=m.get(q.subcategory);x.n++;if(p.reviews){x.reviewed++;x.sum+=p.mastery||0;}}return [...m].map(([name,x])=>({name,mastery:x.reviewed?Math.round(x.sum/x.reviewed):0,reviewed:x.reviewed,total:x.n})).filter(x=>x.reviewed).sort((a,b)=>a.mastery-b.mastery);}
function weakQuestions(){const weak=new Set(topicStats().slice(0,8).map(x=>x.name));return BANK.filter(q=>difficultyOK(q)&&weak.has(q.subcategory)).sort((a,b)=>(prog(a.id).mastery||0)-(prog(b.id).mastery||0));}
function totalStudyMinutes(){return Math.round(S.history.length*1.25);}
function stats(){const reviewed=[...S.progress.values()].filter(p=>p.reviews>0);const mastered=reviewed.filter(p=>p.mastery>=80).length;const today=dayKey(new Date());const todayN=S.history.filter(h=>h.ts&&dayKey(new Date(h.ts))===today).length;const days=new Set(S.history.map(h=>h.ts&&dayKey(new Date(h.ts))).filter(Boolean)).size;return {studied:reviewed.length,mastered,today:todayN,streak:streak(),minutes:totalStudyMinutes(),avg:days?Math.round(S.history.length/days):0};}
function highYield(q){return q.interviewFrequency>=4;}
function core(q){return q.interviewFrequency===5&&(q.difficulty<=4||q.tags?.includes('interview-trap'));}
function getMode(mode,count=20,topic=''){
  let pool=[];
  if(mode==='daily')pool=[...due(),...shuffled(unseen()).slice(0,S.settings.newPerDay)];
  else if(mode==='random')pool=shuffled(BANK.filter(difficultyOK));
  else if(mode==='weak')pool=weakQuestions();
  else if(mode==='high')pool=shuffled(BANK.filter(q=>difficultyOK(q)&&highYield(q)));
  else if(mode==='formula')pool=shuffled(BANK.filter(q=>difficultyOK(q)&&q.formula));
  else if(mode==='calc')pool=shuffled(BANK.filter(q=>difficultyOK(q)&&['Calculation','Mental Math','Mini-Case'].includes(q.questionType)));
  else if(mode==='core')pool=shuffled(BANK.filter(q=>difficultyOK(q)&&core(q)));
  else if(mode==='bookmarks')pool=shuffled(BANK.filter(q=>difficultyOK(q)&&prog(q.id).bookmarked));
  else if(mode==='ma')pool=shuffled(BANK.filter(q=>difficultyOK(q)&&q.category==='M&A'));
  else if(mode==='accounting')pool=shuffled(BANK.filter(q=>difficultyOK(q)&&q.category==='Accounting'));
  else if(mode==='valuation')pool=shuffled(BANK.filter(q=>difficultyOK(q)&&q.category==='Valuation'));
  else if(mode==='markets')pool=shuffled(BANK.filter(q=>difficultyOK(q)&&['Global Markets / Macro','Fixed Income / Derivatives'].includes(q.category)));
  else if(mode==='macro')pool=shuffled(BANK.filter(q=>difficultyOK(q)&&q.category==='Global Markets / Macro'&&/macro|monetary|market reaction|international|fiscal/i.test(q.subcategory+' '+q.topic)));
  else if(mode==='topic')pool=shuffled(BANK.filter(q=>difficultyOK(q)&&(q.category===topic||q.subcategory===topic)));
  else pool=shuffled(BANK.filter(difficultyOK));
  pool=pool.map(q=>({q,key:(prog(q.id).reviews?0:1)+(prog(q.id).mastery||0)/100+Math.random()*.35})).sort((a,b)=>a.key-b.key).map(x=>x.q);
  return pool.slice(0,Math.min(count||20,pool.length));
}
function startSession(mode,count=20,topic=''){const qs=getMode(mode,count,topic);if(!qs.length){toast(t('noQuestions'));return;}S.session={mode,qs,index:0,revealed:false,ratings:{},started:Date.now(),interview:false};S.view='study';render();}
function interviewPool(type,minutes){const n=Math.max(5,Math.ceil(minutes/2.3));let weights;if(type==='M&A Interview')weights=[['Accounting',.18],['Valuation',.24],['M&A',.48],['Mental Math',.10]];else if(type==='Investment Banking Interview')weights=[['Accounting',.23],['Valuation',.28],['M&A',.28],['Corporate Finance',.10],['Mental Math',.11]];else if(type==='Global Markets Interview')weights=[['Global Markets / Macro',.48],['Fixed Income / Derivatives',.28],['LBO / Credit',.10],['Mental Math',.14]];else weights=[['Accounting',.15],['Valuation',.18],['M&A',.24],['Global Markets / Macro',.18],['Fixed Income / Derivatives',.10],['Corporate Finance',.07],['Mental Math',.08]];const out=[];for(const [cat,w] of weights){const k=Math.max(1,Math.round(n*w));const p=shuffled(BANK.filter(q=>q.category===cat&&q.interviewFrequency>=4&&difficultyOK(q)&&(S.settings.difficulty!=='all'||q.difficulty>=2)));out.push(...p.slice(0,k));}return shuffled(out).slice(0,n);}
function startInterview(type,minutes){const qs=interviewPool(type,minutes);if(!qs.length){toast(t('noQuestions'));return;}S.session={mode:type,qs,index:0,revealed:false,ratings:{},started:Date.now(),interview:true,duration:minutes*60};S.view='study';render();}
function nextQuestion(){if(!S.session)return;S.session.index++;S.session.revealed=false;if(S.session.index>=S.session.qs.length)S.view='summary';render();window.scrollTo(0,0);}
function reveal(){if(S.session){S.session.revealed=true;render();}}
function jumpQuestion(id){const q=byId.get(id);if(!q)return;S.session={mode:'Search',qs:[q],index:0,revealed:false,ratings:{},started:Date.now(),interview:false};S.view='study';render();}

// ---------- rendering ----------
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function stars(n){return '★'.repeat(n)+'☆'.repeat(Math.max(0,5-n));}
function difficultyName(v){if(v==='all')return t('allLevels');const en=['','Foundation','Core','Intermediate','Advanced','Expert'];const es=['','Base','Core','Intermedia','Avanzada','Experta'];return `${v} · ${(S.settings.language==='es'?es:en)[Number(v)]}`;}
function shell(content,active='home'){return `<main class="app-shell"><div class="topbar"><div><div class="brand"><span class="brand-mark">CIB</span> INTERVIEW DRILL</div><div class="subtle">${BANK.length.toLocaleString()} ${S.settings.language==='es'?'preguntas técnicas':'substantive questions'} · ${t('offline')}</div></div><div class="top-actions"><button class="lang-btn" data-action="language" aria-label="Language">${S.settings.language==='en'?'EN':'ES'}</button><button class="icon-btn" data-action="theme" aria-label="Toggle theme">◐</button></div></div>${content}</main>${nav(active)}`;}
function nav(active){const items=[['home','⌂',t('today')],['search','⌕',t('search')],['formulas','ƒx',t('formulas')],['progress','◫',t('progress')],['settings','⚙',t('settings')]];return `<nav class="nav">${items.map(([v,i,l])=>`<button data-view="${v}" class="${active===v?'active':''}"><span class="nav-icon">${i}</span>${l}</button>`).join('')}</nav>`;}
function difficultySelector(){return `<div class="filter-card"><div><span class="filter-label">${t('difficulty')}</span><strong>${difficultyName(S.settings.difficulty)}</strong></div><div class="difficulty-row"><button class="diff-chip ${S.settings.difficulty==='all'?'active':''}" data-difficulty="all">${t('allLevels')}</button>${[1,2,3,4,5].map(x=>`<button class="diff-chip ${String(x)===String(S.settings.difficulty)?'active':''}" data-difficulty="${x}">${x}</button>`).join('')}</div></div>`;}
function home(){
  const st=stats(),d=due().length,n=unseen().length,weak=topicStats().slice(0,5);
  const fast=[['random','Quick 5',5,'⚡'],['random','Quick 10',10,'◫'],['high',S.settings.language==='es'?'High-Yield':'High-Yield',20,'★'],['weak',S.settings.language==='es'?'Áreas débiles':'Weak Areas',20,'↗']];
  const focus=[['ma','M&A',S.settings.language==='es'?'Deals, accretion/dilution y PPA':'Deals, accretion/dilution, PPA','deal'],['accounting',S.settings.language==='es'?'Contabilidad':'Accounting',S.settings.language==='es'?'Tres estados y mecánica':'Three statements & mechanics','accounting'],['valuation',S.settings.language==='es'?'Valoración':'Valuation',S.settings.language==='es'?'DCF, comparables y bridge de EV':'DCF, comps & EV bridge','valuation'],['markets',S.settings.language==='es'?'Mercados':'Markets',S.settings.language==='es'?'Tasas, FX, renta fija y derivados':'Rates, FX, FI & derivatives','markets'],['macro',S.settings.language==='es'?'Macro':'Macro',S.settings.language==='es'?'Política monetaria y transmisión cross-asset':'Policy & cross-asset','macro'],['calc',S.settings.language==='es'?'Cálculos':'Calculations',S.settings.language==='es'?'Casos y mental math':'Cases & mental math','calc']];
  return shell(`
  <section class="hero-v2"><div class="hero-orb orb-a"></div><div class="hero-orb orb-b"></div><div class="hero-copy"><div class="eyebrow hero-eye">${t('today')}</div><h1>${d} ${t('reviewsDue')}</h1><p>${Math.min(S.settings.newPerDay,n)} ${t('newReady')} · ${st.streak} ${t('dayStreak')}</p><button class="hero-start" data-start="daily" data-count="${Math.max(10,d+Math.min(S.settings.newPerDay,n))}"><span>▶</span>${t('startDaily')}</button></div><div class="hero-score"><span>${st.today}</span><small>${S.settings.language==='es'?'hechas hoy':'done today'}</small></div></section>
  ${difficultySelector()}
  <div class="grid three home-stats"><div class="card stat stat-blue"><span>${t('studied')}</span><b>${st.studied}</b></div><div class="card stat stat-green"><span>${t('mastered')}</span><b>${st.mastered}</b></div><div class="card stat stat-orange"><span>${t('todayCount')}</span><b>${st.today}</b></div></div>
  <h2 class="section-title">${t('quickPractice')}</h2><div class="quick-row">${fast.map(([m,l,c,ic])=>`<button class="quick-card" data-start="${m}" data-count="${c}"><span class="quick-icon">${ic}</span><b>${l}</b><small>${c} ${S.settings.language==='es'?'preguntas':'questions'}</small></button>`).join('')}</div>
  <h2 class="section-title">${S.settings.language==='es'?'Áreas de enfoque':'Focus areas'}</h2><div class="focus-grid">${focus.map(([m,l,s,cl])=>`<button class="focus-card ${cl}" data-start="${m}" data-count="20"><div class="focus-dot"></div><b>${l}</b><span>${s}</span></button>`).join('')}</div>
  <h2 class="section-title">${t('weakTopics')}</h2><div class="weak-list">${weak.length?weak.map(x=>`<button class="chip" data-topic="${esc(x.name)}">${esc(x.name)} · ${x.mastery}%</button>`).join(''):`<span class="subtle">${S.settings.language==='es'?'Estudia algunas preguntas y aquí aparecerán tus áreas débiles.':'Study a few questions and weak areas will appear here.'}</span>`}</div>
  <h2 class="section-title">${t('byTopic')}</h2><section class="card"><div class="form-row"><label>${t('category')}</label><select id="topic-select"><option value="">${t('chooseCategory')}</option>${[...new Set(BANK.map(q=>q.category))].map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><button class="btn full" data-action="start-topic">${t('startTopic')}</button></section>
  <h2 class="section-title">${t('interviewMode')}</h2><section class="card interview-card"><div class="form-row"><label>${t('interview')}</label><select id="interview-type">${['M&A Interview','Investment Banking Interview','Global Markets Interview','Mixed CIB Interview'].map(x=>`<option ${x===S.settings.interviewType?'selected':''}>${x}</option>`).join('')}</select></div><div class="pill-row">${[10,20,30,45,60].map(x=>`<button class="chip ${x===S.settings.interviewMinutes?'active':''}" data-interview-min="${x}">${x} min</button>`).join('')}</div><button class="btn accent full" style="margin-top:12px" data-action="start-interview">${t('startInterview')}</button></section>
  <h2 class="section-title">${S.settings.language==='es'?'Más práctica':'More practice'}</h2><div class="mode-grid"><button class="mode-card" data-start="core" data-count="30"><b>Core Interview</b><span>${S.settings.language==='es'?'Preguntas imprescindibles':'Must-answer questions'}</span></button><button class="mode-card" data-start="formula" data-count="30"><b>${S.settings.language==='es'?'Solo fórmulas':'Formulas Only'}</b><span>${S.settings.language==='es'?'Recall de fórmulas':'Formula recall cards'}</span></button><button class="mode-card" data-start="bookmarks" data-count="30"><b>${S.settings.language==='es'?'Guardadas':'Bookmarked'}</b><span>${S.settings.language==='es'?'Tus preguntas marcadas':'Saved questions'}</span></button><button class="mode-card" data-start="random" data-count="50"><b>Quick 50</b><span>${S.settings.language==='es'?'Bloque largo':'Deep practice block'}</span></button></div>`,'home');
}
function study(){const ss=S.session;if(!ss||ss.index>=ss.qs.length){S.view='home';return home();}const q=ss.qs[ss.index],p=prog(q.id),note=S.notes.get(q.id)||'',pct=Math.round((ss.index/ss.qs.length)*100);return `<main class="app-shell"><div class="session-head"><button class="btn ghost" data-action="exit">← ${t('exit')}</button><div class="session-count">${ss.index+1} / ${ss.qs.length}</div>${ss.interview?`<div class="interview-timer" id="timer">${fmtTime(Math.max(0,ss.duration-Math.floor((Date.now()-ss.started)/1000)))}</div>`:'<span></span>'}</div><div class="progressbar"><i style="width:${pct}%"></i></div><section class="card question-card" id="question-card"><div class="qmeta"><span class="badge category-badge">${esc(q.category)} › ${esc(q.subcategory)}</span><span class="badge">${stars(q.interviewFrequency)}</span><span class="badge level-badge">LEVEL ${q.difficulty}</span><span class="badge">${esc(q.questionType)}</span></div><button class="star ${p.bookmarked?'on':''}" data-action="bookmark" aria-label="Bookmark">${p.bookmarked?'★':'☆'}</button><div class="question-kicker">${t('question')}</div><h1 class="question">${esc(questionText(q))}</h1>${!ss.revealed?`<button class="btn accent full reveal-btn" data-action="reveal">${t('showAnswer')}</button>`:answerBlock(q,note)}</section>${ss.revealed?`<div class="rating-row"><button class="rating again" data-rate="again">${t('again')}</button><button class="rating hard" data-rate="hard">${t('hard')}</button><button class="rating good" data-rate="good">${t('good')}</button><button class="rating easy" data-rate="easy">${t('easy')}</button></div>`:''}</main>`;}
function answerBlock(q,note){const ctx=contextText(q),defs=definitionsHTML(q);return `<div class="answer"><section class="answer-primary"><h3>${t('interviewResponse')}</h3><p>${esc(answerText(q))}</p></section><section class="answer-section definitions"><h3>${t('definitions')}</h3>${defs}</section>${ctx?`<section class="answer-section complement"><h3>${t('additionalContext')}</h3><p>${esc(ctx)}</p></section>`:''}${q.formula?`<section class="answer-section"><h3>${t('formula')}</h3><div class="formula formula-pretty">${mathHTML(q.formula)}</div></section>`:''}${q.variables?`<section class="answer-section"><h3>${t('variables')}</h3><p>${esc(localText(q.variables))}</p></section>`:''}${q.workedExample?`<section class="answer-section"><h3>${t('workedExample')}</h3><p>${esc(localText(q.workedExample))}</p></section>`:''}${q.commonMistake?`<section class="answer-section mistake"><h3>${t('commonMistake')}</h3><p>${esc(localText(q.commonMistake))}</p></section>`:''}${q.interviewerTrap?`<section class="answer-section trap-box"><h3>${t('interviewTrap')}</h3><p>${esc(localText(q.interviewerTrap))}</p></section>`:''}${q.followUps?.length?`<section class="answer-section"><h3>${t('followUps')}</h3><ul class="summary-list">${q.followUps.map(x=>`<li>${esc(localText(x))}</li>`).join('')}</ul></section>`:''}${S.settings.language==='es'?`<details class="original-en"><summary>${t('originalEnglish')}</summary><p>${esc(q.idealInterviewAnswer)}</p><p class="translation-note">${t('translationNote')}</p></details>`:''}<div class="form-row note-row"><label>${t('personalNote')}</label><textarea id="note" data-id="${esc(q.id)}" placeholder="${esc(t('notePlaceholder'))}">${esc(note)}</textarea></div></div>`;}
function searchView(){const cats=[...new Set(BANK.map(q=>q.category))];let r=[];if(S.query.trim().length>=2){const terms=S.query.toLowerCase().split(/\s+/).filter(Boolean);r=BANK.filter(q=>{const hay=[q.question,questionText(q),q.topic,q.subcategory,q.category,q.idealInterviewAnswer,q.spanishExplanation,q.formula,...(q.relatedConcepts||[])].join(' ').toLowerCase();return terms.every(x=>hay.includes(x));}).slice(0,80);}return shell(`<input class="search" id="search" placeholder="${esc(t('typeSearch'))}" value="${esc(S.query)}" autofocus><div class="pill-row search-cats" style="margin-top:10px">${cats.map(c=>`<button class="chip" data-search-cat="${esc(c)}">${esc(c)}</button>`).join('')}</div><section class="card" style="margin-top:12px">${S.query.trim().length<2?`<div class="empty">${t('typeTwo')}</div>`:r.length?r.map(q=>`<div class="result"><button data-jump="${q.id}"><b>${esc(questionText(q))}</b><span>${esc(q.category)} › ${esc(q.subcategory)} · Level ${q.difficulty}${q.formula?` · ƒx`:''}</span></button></div>`).join(''):`<div class="empty">${t('noMatches')}</div>`}</section>`,'search');}
function formulasView(){const term=S.formulaQuery.toLowerCase();const f=FORMULAS.filter(x=>!term||[x.topic,x.category,x.formula].join(' ').toLowerCase().includes(term)).slice(0,220);return shell(`<input class="search" id="formula-search" placeholder="${esc(t('searchFormulas'))}" value="${esc(S.formulaQuery)}"><section class="grid formula-grid" style="margin-top:12px">${f.map(x=>`<article class="card formula-card"><div class="eyebrow">${esc(x.category)}</div><h3>${esc(x.topic)}</h3><div class="formula formula-pretty">${mathHTML(x.formula)}</div><h4>${t('interpretation')}</h4><p class="subtle">${esc(localText(x.interpretation))}</p><h4>${t('whenUsed')}</h4><p class="subtle">${esc(localText(x.whenUsed))}</p>${x.variables?`<h4>${t('variables')}</h4><p class="subtle">${esc(localText(x.variables))}</p>`:''}<details><summary>${t('commonMistake')}</summary><p>${esc(localText(x.commonMistake||''))}</p></details></article>`).join('')}</section>`,'formulas');}
function progressView(){const st=stats(),topics=topicStats().slice().sort((a,b)=>b.reviewed-a.reviewed).slice(0,25),recent=S.history.filter(h=>['again','hard'].includes(h.rating)).slice(-12).reverse();return shell(`<div class="grid three"><div class="card stat"><span class="subtle">${t('studied')}</span><b>${st.studied}</b></div><div class="card stat"><span class="subtle">${t('mastered')}</span><b>${st.mastered}</b></div><div class="card stat"><span class="subtle">${S.settings.language==='es'?'Racha':'Current streak'}</span><b>${st.streak}</b></div></div><h2 class="section-title">${S.settings.language==='es'?'Dominio por tema':'Topic mastery'}</h2><section class="card">${topics.length?topics.map(x=>`<div class="topic-row"><div class="name">${esc(x.name)}</div><div class="bar"><i style="width:${x.mastery}%"></i></div><div class="pct">${x.mastery}%</div></div>`).join(''):`<div class="empty">${S.settings.language==='es'?'Tu panel se llenará a medida que estudies.':'Your mastery dashboard will populate as you study.'}</div>`}</section><h2 class="section-title">${S.settings.language==='es'?'Errores recientes':'Recent mistakes'}</h2><section class="card">${recent.length?recent.map(h=>{const q=byId.get(h.id);return q?`<div class="result"><button data-jump="${q.id}"><b>${esc(questionText(q))}</b><span>${esc(h.rating.toUpperCase())} · ${esc(q.subcategory)}</span></button></div>`:''}).join(''):`<div class="empty">${S.settings.language==='es'?'No hay Again/Hard recientes.':'No recent Again/Hard ratings.'}</div>`}</section>`,'progress');}
function settingsView(){return shell(`<section class="card"><h2>${t('studySettings')}</h2><div class="form-row"><label>${t('language')}</label><select id="language"><option value="en" ${S.settings.language==='en'?'selected':''}>English</option><option value="es" ${S.settings.language==='es'?'selected':''}>Español</option></select></div><div class="form-row"><label>${t('difficulty')}</label><select id="difficulty"><option value="all" ${S.settings.difficulty==='all'?'selected':''}>${t('allLevels')}</option>${[1,2,3,4,5].map(x=>`<option value="${x}" ${String(x)===String(S.settings.difficulty)?'selected':''}>${difficultyName(x)}</option>`).join('')}</select></div><div class="form-row"><label>${t('dailyGoal')}</label><select id="daily-goal">${[10,20,30,50,75,100].map(x=>`<option value="${x}" ${x===S.settings.dailyGoal?'selected':''}>${x} ${S.settings.language==='es'?'preguntas/día':'questions/day'}</option>`).join('')}</select></div><div class="form-row"><label>${t('newQuestions')}</label><select id="new-day">${[5,10,15,20,30,50].map(x=>`<option value="${x}" ${x===S.settings.newPerDay?'selected':''}>${x}</option>`).join('')}</select></div><div class="form-row"><label>${t('theme')}</label><select id="theme">${['system','light','dark'].map(x=>`<option value="${x}" ${x===S.settings.theme?'selected':''}>${x}</option>`).join('')}</select></div></section><h2 class="section-title">${t('data')}</h2><section class="card"><button class="btn full" data-action="export">${t('exportBackup')}</button><label class="btn full import-label">${t('importBackup')}<input id="import" type="file" accept="application/json" hidden></label><button class="btn danger full" style="margin-top:10px" data-action="reset">${t('resetProgress')}</button><p class="subtle">${S.settings.language==='es'?'El backup incluye progreso, historial, bookmarks, notas, ajustes y días de estudio.':'Backup includes progress, review history, bookmarks, notes, settings and study dates.'}</p></section><h2 class="section-title">Offline</h2><section class="card"><p>${S.settings.language==='es'?'Una vez cargada, la app y el banco principal quedan en caché para estudiar offline. En iPhone, añádela a la pantalla de inicio desde Safari.':'Once loaded, the core bank and app shell are cached for offline study. Add this site to your iPhone Home Screen from Safari for standalone use.'}</p></section>`,'settings');}
function summaryView(){const ss=S.session||{ratings:{},qs:[],started:Date.now()},missed=ss.qs.filter(q=>['again','hard'].includes(ss.ratings[q.id])),topics=[...new Set(missed.map(q=>q.subcategory))],elapsed=Math.round((Date.now()-ss.started)/60000);return shell(`<section class="card hero"><div class="eyebrow">${t('sessionComplete')}</div><h1>${ss.qs.length} ${S.settings.language==='es'?'preguntas':'questions'}</h1><p class="subtle">${elapsed} min · ${missed.length} Again/Hard</p><button class="btn accent full" data-view="home">${t('backToday')}</button></section><h2 class="section-title">${t('topicsMissed')}</h2><section class="card">${topics.length?`<ul class="summary-list">${topics.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<p>${t('noWeak')}</p>`}</section><h2 class="section-title">${t('questionsReview')}</h2><section class="card">${missed.length?missed.map(q=>`<div class="result"><button data-jump="${q.id}"><b>${esc(questionText(q))}</b><span>${esc(ss.ratings[q.id].toUpperCase())} · ${esc(q.subcategory)}</span></button></div>`).join(''):`<div class="empty">${t('strongSession')}</div>`}</section>`,'home');}
function render(){let html;if(S.view==='home')html=home();else if(S.view==='study')html=study();else if(S.view==='search')html=searchView();else if(S.view==='formulas')html=formulasView();else if(S.view==='progress')html=progressView();else if(S.view==='settings')html=settingsView();else if(S.view==='summary')html=summaryView();else html=home();document.getElementById('app').innerHTML=html;wireTimer();}
function fmtTime(s){const m=Math.floor(s/60),r=s%60;return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`;}
let timerInt;function wireTimer(){clearInterval(timerInt);if(S.view==='study'&&S.session?.interview){timerInt=setInterval(()=>{const el=document.getElementById('timer');if(!el)return;const left=Math.max(0,S.session.duration-Math.floor((Date.now()-S.session.started)/1000));el.textContent=fmtTime(left);},1000);}}
function toast(msg){const x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),1800);}
function applyTheme(){const x=S.settings.theme;document.documentElement.dataset.theme=x==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):x;document.documentElement.lang=S.settings.language==='es'?'es':'en';}
function cycleTheme(){S.settings.theme=S.settings.theme==='light'?'dark':S.settings.theme==='dark'?'system':'light';saveSettings();render();toast(`Theme: ${S.settings.theme}`);}
function cycleLanguage(){S.settings.language=S.settings.language==='en'?'es':'en';saveSettings();render();}

// ---------- backup ----------
async function exportBackup(){const payload={version:2,exportedAt:new Date().toISOString(),bankQuestions:BANK.length,progress:[...S.progress.values()],notes:[...S.notes].map(([id,text])=>({id,text})),history:S.history,settings:S.settings,studyDays:JSON.parse(localStorage.getItem('cib-study-days')||'[]')};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cib-drill-backup-${dayKey(new Date())}.json`;a.click();URL.revokeObjectURL(a.href);}
async function importBackup(file){try{const x=JSON.parse(await file.text());if(![1,2].includes(x.version)||!Array.isArray(x.progress)||!Array.isArray(x.history))throw new Error('Invalid backup');await clearStore('progress');await clearStore('notes');await clearStore('history');S.progress.clear();S.notes.clear();S.history=[];for(const p of x.progress){S.progress.set(p.id,p);await put('progress',p);}for(const n of x.notes||[]){S.notes.set(n.id,n.text||'');await put('notes',n);}for(const h of x.history){S.history.push(h);await add('history',h);}S.settings={...DEFAULTS,...(x.settings||{})};saveSettings();localStorage.setItem('cib-study-days',JSON.stringify(x.studyDays||[]));render();toast(S.settings.language==='es'?'Backup restaurado':'Backup restored');}catch(e){toast(S.settings.language==='es'?'No se pudo importar el backup':'Could not import backup');}}
async function resetAll(){if(!confirm(S.settings.language==='es'?'¿Reiniciar todo el progreso, bookmarks, notas e historial?':'Reset all study progress, bookmarks, notes and review history?'))return;await Promise.all([clearStore('progress'),clearStore('notes'),clearStore('history')]);S.progress.clear();S.notes.clear();S.history=[];localStorage.removeItem('cib-study-days');render();toast(S.settings.language==='es'?'Progreso reiniciado':'Progress reset');}

// ---------- events ----------
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-action],[data-view],[data-start],[data-topic],[data-jump],[data-interview-min],[data-difficulty],[data-search-cat]');if(!b)return;if(b.dataset.view){S.view=b.dataset.view;S.session=null;render();window.scrollTo(0,0);return;}if(b.dataset.start){startSession(b.dataset.start,Number(b.dataset.count)||20);return;}if(b.dataset.topic){startSession('topic',20,b.dataset.topic);return;}if(b.dataset.jump){jumpQuestion(b.dataset.jump);return;}if(b.dataset.rate){rate(S.session.qs[S.session.index].id,b.dataset.rate);return;}if(b.dataset.interviewMin){S.settings.interviewMinutes=Number(b.dataset.interviewMin);saveSettings();render();return;}if(b.dataset.difficulty){S.settings.difficulty=b.dataset.difficulty;saveSettings();render();return;}if(b.dataset.searchCat){S.query=b.dataset.searchCat;render();return;}const a=b.dataset.action;if(a==='theme')cycleTheme();if(a==='language')cycleLanguage();if(a==='reveal')reveal();if(a==='exit'){S.session=null;S.view='home';render();}if(a==='bookmark'){const id=S.session.qs[S.session.index].id,p={...prog(id),bookmarked:!prog(id).bookmarked};S.progress.set(id,p);put('progress',p);render();}if(a==='start-topic'){const sel=document.getElementById('topic-select');if(sel?.value)startSession('topic',30,sel.value);else toast(S.settings.language==='es'?'Elige una categoría primero.':'Choose a category first.');}if(a==='start-interview'){const sel=document.getElementById('interview-type');S.settings.interviewType=sel?.value||S.settings.interviewType;saveSettings();startInterview(S.settings.interviewType,S.settings.interviewMinutes);}if(a==='export')exportBackup();if(a==='reset')resetAll();});
document.addEventListener('input',e=>{if(e.target.id==='search'){S.query=e.target.value;clearTimeout(S.searchTimer);S.searchTimer=setTimeout(()=>render(),120);}if(e.target.id==='formula-search'){S.formulaQuery=e.target.value;clearTimeout(S.searchTimer);S.searchTimer=setTimeout(()=>render(),120);}if(e.target.id==='note'){const id=e.target.dataset.id,text=e.target.value;S.notes.set(id,text);clearTimeout(e.target._t);e.target._t=setTimeout(()=>put('notes',{id,text}),250);}});
document.addEventListener('change',e=>{if(e.target.id==='daily-goal'){S.settings.dailyGoal=Number(e.target.value);saveSettings();}if(e.target.id==='new-day'){S.settings.newPerDay=Number(e.target.value);saveSettings();}if(e.target.id==='theme'){S.settings.theme=e.target.value;saveSettings();render();}if(e.target.id==='language'){S.settings.language=e.target.value;saveSettings();render();}if(e.target.id==='difficulty'){S.settings.difficulty=e.target.value;saveSettings();render();}if(e.target.id==='interview-type'){S.settings.interviewType=e.target.value;saveSettings();}if(e.target.id==='import'&&e.target.files?.[0])importBackup(e.target.files[0]);});
let tx=null;document.addEventListener('touchstart',e=>{if(S.view==='study'&&S.session?.revealed)tx=e.changedTouches[0].clientX;},{passive:true});document.addEventListener('touchend',e=>{if(tx==null||S.view!=='study'||!S.session?.revealed)return;const dx=e.changedTouches[0].clientX-tx;tx=null;if(Math.abs(dx)<90)return;rate(S.session.qs[S.session.index].id,dx>0?'good':'again');},{passive:true});

async function boot(){if(!BANK.length){app.innerHTML='<div class="empty">Question bank failed to load.</div>';return;}await load();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});}
boot().catch(err=>{console.error(err);app.innerHTML=`<div class="empty">Could not start the app: ${esc(err.message)}</div>`;});
})();
